/**
 * Help Article Seed Script — migrates static DEFAULT_HELP_ARTICLES into the
 * HelpArticle + ArticleSection tables for the default tenant. Idempotent:
 * upserts by (tenantId, slug) and resyncs sections by delete-then-create.
 *
 * Run:
 *   pnpm --filter @intelliflow/db db:seed:help-articles
 *
 * @see .specify/sprints/sprint-17/specifications/IFC-300-spec.md
 * @see .specify/sprints/sprint-17/planning/IFC-300-plan.md
 */
import { PrismaClient } from '../generated/prisma/client';
import { PrismaPg } from '@prisma/adapter-pg';
import { SEED_IDS } from '../src/seed-ids';
import snapshot from './data/help-articles.snapshot.json';

interface SeedArticleSection {
  readonly heading: string;
  readonly content: string;
  readonly blocks?: readonly unknown[];
}

interface SeedArticle {
  readonly id: string;
  readonly slug: string;
  readonly title: string;
  readonly categoryId: string;
  readonly excerpt: string;
  readonly sections: readonly SeedArticleSection[];
  readonly readTimeMinutes: number;
  readonly lastUpdatedAt: string;
  readonly keywords: readonly string[];
  readonly relatedArticleIds: readonly string[];
  readonly order: number;
}

// Data is loaded from a local JSON snapshot generated by
// `scripts/generate-help-articles-snapshot.ts`, which reads the
// authoritative source at `apps/web/src/lib/support/help-articles.ts`.
// This indirection avoids a cross-workspace import that would violate
// `packages/db/tsconfig.json`'s rootDir constraint. Regenerate the
// snapshot with `pnpm --filter @intelliflow/db run db:snapshot:help-articles`
// whenever the apps/web source changes.
export function assertSnapshotShape(
  value: unknown
): asserts value is { articles: readonly SeedArticle[] } {
  if (!value || typeof value !== 'object' || !('articles' in value)) {
    throw new Error('help-articles.snapshot.json: missing "articles" property');
  }
  const articles = (value as { articles: unknown }).articles;
  if (!Array.isArray(articles) || articles.length === 0) {
    throw new Error('help-articles.snapshot.json: "articles" must be a non-empty array');
  }
  for (const article of articles as readonly unknown[]) {
    if (!article || typeof article !== 'object') {
      throw new Error('help-articles.snapshot.json: each article must be an object');
    }
    const a = article as Record<string, unknown>;
    if (typeof a.slug !== 'string' || typeof a.title !== 'string' || !Array.isArray(a.sections)) {
      throw new Error(
        `help-articles.snapshot.json: article missing required fields (slug/title/sections) — got ${JSON.stringify(a).slice(0, 120)}`
      );
    }
  }
}

assertSnapshotShape(snapshot);
const DEFAULT_HELP_ARTICLES = snapshot.articles;

type SeedPrismaClient = Pick<
  PrismaClient,
  'tenant' | 'helpArticle' | 'articleSection' | '$disconnect'
>;

let cachedClient: SeedPrismaClient | null = null;

export function getPrisma(): SeedPrismaClient {
  if (!cachedClient) {
    const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
    cachedClient = new PrismaClient({ adapter }) as unknown as SeedPrismaClient;
  }
  return cachedClient;
}

/** Test-only injection hook. Must NOT be called from production code. */
export function __setPrismaForTest(mock: SeedPrismaClient | null): void {
  if (process.env.NODE_ENV === 'production') {
    throw new Error('__setPrismaForTest is not callable in production');
  }
  cachedClient = mock;
}

export const EXPECTED_ARTICLES = DEFAULT_HELP_ARTICLES.length;
export const EXPECTED_SECTIONS = DEFAULT_HELP_ARTICLES.reduce(
  (sum, article) => sum + article.sections.length,
  0
);
/** Test-only fixtures. Exposed so tests can verify keyword/relatedId passthrough without a cross-workspace import of the source data. */
export const __TEST_FIXTURES__ = {
  firstSlug: DEFAULT_HELP_ARTICLES[0].slug,
  firstKeywords: DEFAULT_HELP_ARTICLES[0].keywords,
  firstRelatedIds: DEFAULT_HELP_ARTICLES[0].relatedArticleIds,
  allSlugs: DEFAULT_HELP_ARTICLES.map((a) => a.slug),
  sectionCounts: new Map(DEFAULT_HELP_ARTICLES.map((a) => [a.slug, a.sections.length])),
} as const;

async function getDefaultTenant() {
  const prisma = getPrisma();
  const expectedId = SEED_IDS.tenant.default;
  const existing = await prisma.tenant.findUnique({ where: { id: expectedId } });
  if (existing) {
    console.log(`🏢 Using existing default tenant (${existing.id})`);
    return existing;
  }
  console.log(`🏢 Creating default tenant (${expectedId})`);
  return prisma.tenant.create({
    data: {
      id: expectedId,
      slug: 'default',
      name: 'Default Tenant',
    },
  });
}

async function seedArticle(tenantId: string, article: (typeof DEFAULT_HELP_ARTICLES)[number]) {
  const prisma = getPrisma();
  const publishedAt = new Date(article.lastUpdatedAt);
  const data = {
    slug: article.slug,
    title: article.title,
    categoryId: article.categoryId,
    excerpt: article.excerpt,
    readTimeMinutes: article.readTimeMinutes,
    keywords: [...article.keywords],
    relatedArticleIds: [...article.relatedArticleIds],
    order: article.order,
    status: 'PUBLISHED' as const,
    publishedAt,
  };
  return prisma.helpArticle.upsert({
    where: { tenantId_slug: { tenantId, slug: article.slug } },
    create: { ...data, tenantId },
    update: data,
  });
}

async function syncSections(
  tenantId: string,
  articleId: string,
  sections: (typeof DEFAULT_HELP_ARTICLES)[number]['sections']
) {
  const prisma = getPrisma();
  await prisma.articleSection.deleteMany({ where: { articleId } });
  for (let index = 0; index < sections.length; index++) {
    const section = sections[index];
    const blocks = section.blocks;
    await prisma.articleSection.create({
      data: {
        heading: section.heading,
        content: section.content,
        ...(blocks !== undefined ? { blocks: [...blocks] } : {}),
        order: index,
        articleId,
        tenantId,
      },
    });
  }
}

async function validate(tenantId: string) {
  const prisma = getPrisma();
  const articleCount = await prisma.helpArticle.count({ where: { tenantId } });
  const sectionCount = await prisma.articleSection.count({ where: { tenantId } });
  if (articleCount !== EXPECTED_ARTICLES || sectionCount !== EXPECTED_SECTIONS) {
    console.error(
      `❌ Validation failed: expected ${EXPECTED_ARTICLES} articles / ${EXPECTED_SECTIONS} sections, got ${articleCount} articles / ${sectionCount} sections`
    );
    process.exit(1);
    return;
  }
  console.log(
    `✅ Validated ${articleCount} articles / ${sectionCount} sections for tenant ${tenantId}`
  );
}

export async function main() {
  const tenant = await getDefaultTenant();
  console.log(`📚 Seeding ${EXPECTED_ARTICLES} help articles...`);
  for (const article of DEFAULT_HELP_ARTICLES) {
    const row = await seedArticle(tenant.id, article);
    await syncSections(tenant.id, row.id, article.sections);
  }
  await validate(tenant.id);
  console.log(`✅ Seeded ${EXPECTED_ARTICLES} help articles for tenant ${tenant.id}`);
}

export async function runAndExit() {
  const prisma = getPrisma();
  try {
    await main();
  } catch (error) {
    console.error(error);
    process.exit(1);
  } finally {
    await prisma.$disconnect();
  }
}
