/**
 * Dynamic Current State Report Generator
 *
 * Builds a task-backed report from `.specify` attestations and the canonical
 * sprint-plan CSV. Existing sprint summary files are used only for sprint
 * titles and are regenerated by the CLI.
 */

import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join, relative } from 'node:path';

import Papa from 'papaparse';

import { parseDependencies } from './data-sync/csv-mapping';
import { readJsonTolerant } from './data-sync/file-io';

interface CsvTaskRow {
  'Task ID': string;
  Section: string;
  Description: string;
  Dependencies: string;
  'Definition of Done': string;
  Status: string;
  'Target Sprint': string;
}

interface NormalizedDoDItem {
  criterion: string;
  met: boolean | null;
  evidence?: string;
}

interface ValidationSummary {
  total: number;
  passed: number;
  failed: number;
  failingNames: string[];
}

interface KpiSummary {
  total: number;
  met: number;
  missed: number;
}

interface NormalizedAttestation {
  taskId: string;
  sprintFolder: number | null;
  path: string;
  verdict: string | null;
  title: string | null;
  notes: string;
  blockerDescription: string;
  invariants: string[];
  definitionOfDoneItems: NormalizedDoDItem[];
  validationSummary: ValidationSummary;
  kpiSummary: KpiSummary;
  timestamp: string | null;
}

export interface ReportTask {
  taskId: string;
  sprint: number | 'Continuous';
  status: string;
  section: string;
  title: string;
  description: string;
  summary: string;
  definitionOfDone: string;
  definitionOfDoneSnapshot: string;
  dependencies: string[];
  attestation: {
    exists: boolean;
    path: string | null;
    verdict: string | null;
    timestamp: string | null;
    sprintFolder: number | null;
  };
  validationSummary: ValidationSummary;
  kpiSummary: KpiSummary;
}

export interface SprintReport {
  sprint: number;
  name: string;
  summarySource: 'specify' | 'metrics' | 'synthetic';
  totalTasks: number;
  completedTasks: number;
  backlogTasks: number;
  blockedTasks: number;
  inProgressTasks: number;
  attestedCompletedTasks: number;
  missingCompletedAttestations: string[];
  context: string;
  notableCompleted: ReportTask[];
  openTasks: ReportTask[];
  sectionSummary: Array<{
    section: string;
    total: number;
    completed: number;
    open: number;
  }>;
  tasks: ReportTask[];
}

export interface CurrentStateReportData {
  generatedAt: string;
  sources: {
    metricsDir: string;
    specifySprintsDir: string;
    csvFiles: string[];
    sourceFiles: string[];
  };
  overview: {
    numberedSprintCount: number;
    numberedSprintRange: string;
    totalTasks: number;
    totalNumberedSprintTasks: number;
    continuousTaskCount: number;
    completedTasks: number;
    backlogTasks: number;
    blockedTasks: number;
    completionPercentage: number;
    inProgressTasks: number;
    otherTasks: number;
  };
  inconsistencies: {
    missingSpecifySprintSummaries: number[];
    ignoredSpecifySprintDirs: string[];
    completedWithoutCanonicalAttestation: string[];
    attestedButNotCompletedInCsv: Array<{
      taskId: string;
      status: string;
      sprint: number | 'Continuous';
      attestationPath: string;
    }>;
    duplicateCanonicalAttestations: Array<{
      taskId: string;
      kept: string;
      skipped: string[];
    }>;
    sprintMismatches: Array<{
      taskId: string;
      csvSprint: number;
      attestationSprint: number;
    }>;
  };
  continuousTasks: ReportTask[];
  currentState: {
    blockedTasks: ReportTask[];
    readyToStart: ReportTask[];
    activeFocusSprints: number[];
  };
  sprints: SprintReport[];
}

export interface CurrentStateReportResult {
  markdown: string;
  data: CurrentStateReportData;
}

type SprintNameEntry = {
  name: string;
  source: 'specify' | 'metrics';
};

function toRepoRelative(repoRoot: string, absolutePath: string): string {
  return relative(repoRoot, absolutePath).replaceAll('\\', '/');
}

function normalizeWhitespace(value: string): string {
  return value.replaceAll(/\s+/g, ' ').trim();
}

function isCompletedStatus(status: string): boolean {
  const normalized = normalizeWhitespace(status).toLowerCase();
  return normalized === 'done' || normalized === 'completed';
}

function flattenText(value: unknown): string {
  if (typeof value === 'string') return normalizeWhitespace(value);
  if (Array.isArray(value)) {
    return normalizeWhitespace(
      value
        .map((entry) => {
          if (typeof entry === 'string') return normalizeWhitespace(entry);
          if (entry && typeof entry === 'object') return normalizeWhitespace(JSON.stringify(entry));
          return '';
        })
        .filter(Boolean)
        .join(' ')
    );
  }
  if (value && typeof value === 'object') return normalizeWhitespace(JSON.stringify(value));
  return '';
}

function summarizeText(value: string, maxLength = 220): string {
  const normalized = normalizeWhitespace(value);
  if (!normalized) return '';
  if (normalized.length <= maxLength) return normalized;

  const punctuationMatches = ['. ', '; ', ' — ', ': ']
    .map((token) => normalized.lastIndexOf(token, maxLength))
    .filter((index) => index >= 80);
  const cutoff = punctuationMatches.length > 0 ? Math.max(...punctuationMatches) + 1 : maxLength;
  return `${normalized.slice(0, cutoff).trim()}...`;
}

function stripNarrativeBoilerplate(value: string): string {
  let cleaned = normalizeWhitespace(value);
  const patterns = [
    /\b\d+\/\d+\s+validations passed\b\.?/gi,
    /\b\d+\/\d+\s+DoD items met\b\.?/gi,
    /\b\d+\/\d+\s+KPIs met\b\.?/gi,
    /\battestation verdict:\s*[A-Z_]+\b\.?/gi,
    /\bAttestation created by batch integrity repair to satisfy completion integrity check\.?/gi,
    /\bCompliance check passed\.?/gi,
    /\b[A-Z]{2,}-\d+\s+(?:exec session completed|implementation complete|repair)\.?\s*/gi,
    /\bRe-execution of [A-Z]{2,}-\d+\.?\s*/gi,
    /\bStatement coverage [^.]+\.?/gi,
    /\bbranch coverage [^.]+\.?/gi,
    /\bfunction coverage [^.]+\.?/gi,
  ];

  for (const pattern of patterns) {
    cleaned = cleaned.replace(pattern, ' ');
  }

  return normalizeWhitespace(cleaned);
}

function normalizeDefinitionOfDoneText(value: string): string {
  const segments = value
    .split(';')
    .map((segment) => normalizeWhitespace(segment))
    .filter(Boolean)
    .filter(
      (segment) =>
        !/^artifacts:/i.test(segment) &&
        !/^verified by:/i.test(segment) &&
        !/^targets:/i.test(segment) &&
        !/^gates:/i.test(segment)
    );

  const normalized = segments.length > 0 ? segments.join('; ') : normalizeWhitespace(value);
  return normalized
    .replace(/\bResponse\s*</gi, 'response under ')
    .replace(/\bLighthouse\s*≥\s*/gi, 'Lighthouse ')
    .replace(/\bTTI\s*</gi, 'TTI under ');
}

function extractSprintNumberFromDirName(name: string): number | null {
  const match = /^sprint-(\d+)$/.exec(name);
  return match ? Number(match[1]) : null;
}

function parseTimestamp(value: unknown): string | null {
  return typeof value === 'string' && value.trim().length > 0 ? value : null;
}

function coerceBoolean(value: unknown): boolean | null {
  if (typeof value === 'boolean') return value;
  if (typeof value === 'string') {
    const normalized = value.trim().toLowerCase();
    if (normalized === 'pass' || normalized === 'passed' || normalized === 'complete') return true;
    if (normalized === 'fail' || normalized === 'failed' || normalized === 'incomplete')
      return false;
  }
  return null;
}

function normalizeDoDItems(raw: unknown): NormalizedDoDItem[] {
  if (!Array.isArray(raw)) return [];
  return raw
    .map<NormalizedDoDItem | null>((entry) => {
      if (!entry || typeof entry !== 'object') return null;
      const item = entry as Record<string, unknown>;
      const criterion = flattenText(item['criterion'] ?? item['item']);
      if (!criterion) return null;
      return {
        criterion,
        met: coerceBoolean(item['met'] ?? item['status']),
        evidence: flattenText(item['evidence']),
      } satisfies NormalizedDoDItem;
    })
    .filter((entry): entry is NormalizedDoDItem => entry !== null);
}

function normalizeStringArray(raw: unknown): string[] {
  if (!Array.isArray(raw)) return [];
  return raw.map((entry) => flattenText(entry)).filter(Boolean);
}

function normalizeValidationSummary(raw: unknown): ValidationSummary {
  if (!Array.isArray(raw)) return { total: 0, passed: 0, failed: 0, failingNames: [] };

  let total = 0;
  let passed = 0;
  let failed = 0;
  const failingNames: string[] = [];

  for (const entry of raw) {
    if (!entry || typeof entry !== 'object') continue;
    total += 1;
    const result = entry as Record<string, unknown>;
    const pass = coerceBoolean(result['passed'] ?? result['status']);
    const name = flattenText(result['name'] ?? result['validation_name'] ?? result['validation']);
    if (pass === true) passed += 1;
    else if (pass === false) {
      failed += 1;
      if (name) failingNames.push(name);
    }
  }

  return { total, passed, failed, failingNames };
}

function normalizeKpiSummary(raw: unknown): KpiSummary {
  if (Array.isArray(raw)) {
    let total = 0;
    let met = 0;
    let missed = 0;
    for (const entry of raw) {
      if (!entry || typeof entry !== 'object') continue;
      total += 1;
      const result = entry as Record<string, unknown>;
      const pass = coerceBoolean(result['met'] ?? result['status']);
      if (pass === true) met += 1;
      else if (pass === false) missed += 1;
    }
    return { total, met, missed };
  }

  if (raw && typeof raw === 'object') return normalizeKpiSummary(Object.values(raw));
  return { total: 0, met: 0, missed: 0 };
}

function loadSprintPlanRows(
  metricsDir: string,
  repoRoot: string
): { rows: CsvTaskRow[]; csvFiles: string[]; sourceFiles: string[] } {
  const globalDir = join(metricsDir, '_global');
  const fullCsvPath = join(globalDir, 'Sprint_plan.csv');
  const csvPaths = existsSync(fullCsvPath) ? [fullCsvPath] : [];

  const rows: CsvTaskRow[] = [];
  for (const csvPath of csvPaths) {
    const parsed = Papa.parse<CsvTaskRow>(readFileSync(csvPath, 'utf-8'), {
      header: true,
      skipEmptyLines: true,
    });
    for (const row of parsed.data) {
      if (row['Task ID']) rows.push(row);
    }
  }

  const csvFiles = csvPaths.map((path) => toRepoRelative(repoRoot, path));
  return { rows, csvFiles, sourceFiles: csvFiles };
}

function loadSprintNames(
  metricsDir: string,
  specifySprintsDir: string,
  repoRoot: string
): { names: Map<number, SprintNameEntry>; sourceFiles: string[] } {
  const names = new Map<number, SprintNameEntry>();
  const sourceFiles: string[] = [];

  const loadFromRoot = (rootDir: string, source: 'specify' | 'metrics'): void => {
    if (!existsSync(rootDir)) return;
    for (const dirent of readdirSync(rootDir, { withFileTypes: true })) {
      if (!dirent.isDirectory()) continue;
      const sprintNumber = extractSprintNumberFromDirName(dirent.name);
      if (sprintNumber === null) continue;
      const summaryPath = join(rootDir, dirent.name, '_summary.json');
      if (!existsSync(summaryPath)) continue;
      try {
        const summary = readJsonTolerant(summaryPath) as { name?: unknown };
        const name = flattenText(summary?.name);
        if (!name) continue;
        if (!names.has(sprintNumber) || source === 'specify') {
          names.set(sprintNumber, { name, source });
        }
        sourceFiles.push(toRepoRelative(repoRoot, summaryPath));
      } catch {
        // invalid summary files are ignored; the report synthesizes when needed
      }
    }
  };

  loadFromRoot(specifySprintsDir, 'specify');
  loadFromRoot(metricsDir, 'metrics');
  return { names, sourceFiles };
}

function normalizeAttestation(
  raw: Record<string, unknown>,
  taskId: string,
  path: string,
  sprintFolder: number | null
): NormalizedAttestation {
  return {
    taskId,
    sprintFolder,
    path,
    verdict:
      ((() => {
        const value = flattenText(raw['verdict']).toUpperCase();
        if (value === 'PASS') return 'COMPLETE';
        return value || null;
      })() as string | null),
    title: flattenText(raw['task_title'] ?? raw['title'] ?? raw['description'] ?? raw['summary']) || null,
    notes: flattenText(raw['notes']),
    blockerDescription:
      raw['blocker'] && typeof raw['blocker'] === 'object'
        ? flattenText((raw['blocker'] as Record<string, unknown>)['description'])
        : flattenText(raw['blocker']),
    invariants:
      raw['context_acknowledgment'] && typeof raw['context_acknowledgment'] === 'object'
        ? normalizeStringArray(
            (raw['context_acknowledgment'] as Record<string, unknown>)['invariants_acknowledged']
          )
        : [],
    definitionOfDoneItems: normalizeDoDItems(raw['definition_of_done_items']),
    validationSummary: normalizeValidationSummary(
      raw['validation_results'] ?? raw['validations']
    ),
    kpiSummary: normalizeKpiSummary(raw['kpi_results'] ?? raw['kpis']),
    timestamp:
      parseTimestamp(raw['attestation_timestamp']) ??
      parseTimestamp(raw['timestamp']) ??
      parseTimestamp(raw['completed_at']) ??
      parseTimestamp(raw['completedAt']) ??
      null,
  };
}

function shouldKeepCandidate(
  existing: NormalizedAttestation,
  candidate: NormalizedAttestation,
  expectedSprint: number | 'Continuous' | undefined
): boolean {
  const existingMatches =
    typeof expectedSprint === 'number' && existing.sprintFolder === expectedSprint;
  const candidateMatches =
    typeof expectedSprint === 'number' && candidate.sprintFolder === expectedSprint;
  if (candidateMatches !== existingMatches) {
    return candidateMatches;
  }
  const existingTime = Date.parse(existing.timestamp ?? '') || 0;
  const candidateTime = Date.parse(candidate.timestamp ?? '') || 0;
  return candidateTime > existingTime;
}

function processTaskAttestation(
  taskDir: { name: string },
  attestationRoot: string,
  sprintNumber: number,
  repoRoot: string,
  expectedSprintByTaskId: Map<string, number | 'Continuous'>,
  byTaskId: Map<string, NormalizedAttestation>,
  duplicateBuckets: Map<string, string[]>,
  sourceFiles: string[]
): void {
  const attestationPath = join(attestationRoot, taskDir.name, 'attestation.json');
  if (!existsSync(attestationPath)) return;
  sourceFiles.push(toRepoRelative(repoRoot, attestationPath));

  try {
    const raw = readJsonTolerant(attestationPath) as Record<string, unknown>;
    const taskId = flattenText(raw['task_id'] ?? raw['taskId']) || taskDir.name;
    const normalized = normalizeAttestation(raw, taskId, attestationPath, sprintNumber);
    const existing = byTaskId.get(taskId);

    if (!existing) {
      byTaskId.set(taskId, normalized);
      return;
    }

    const expectedSprint = expectedSprintByTaskId.get(taskId);
    duplicateBuckets.set(taskId, [
      ...(duplicateBuckets.get(taskId) ?? [toRepoRelative(repoRoot, existing.path)]),
      toRepoRelative(repoRoot, normalized.path),
    ]);

    if (shouldKeepCandidate(existing, normalized, expectedSprint)) {
      byTaskId.set(taskId, normalized);
    }
  } catch {
    // malformed attestation files are ignored and surfaced via evidence gaps
  }
}

function processSprintAttestations(
  sprintDir: { name: string; isDirectory: () => boolean },
  specifySprintsDir: string,
  repoRoot: string,
  expectedSprintByTaskId: Map<string, number | 'Continuous'>,
  byTaskId: Map<string, NormalizedAttestation>,
  duplicateBuckets: Map<string, string[]>,
  ignoredSpecifySprintDirs: string[],
  sourceFiles: string[]
): void {
  if (!sprintDir.isDirectory() || !sprintDir.name.startsWith('sprint-')) return;
  const sprintNumber = extractSprintNumberFromDirName(sprintDir.name);
  if (sprintNumber === null) {
    ignoredSpecifySprintDirs.push(sprintDir.name);
    return;
  }

  const attestationRoot = join(specifySprintsDir, sprintDir.name, 'attestations');
  if (!existsSync(attestationRoot)) return;

  for (const taskDir of readdirSync(attestationRoot, { withFileTypes: true })) {
    if (!taskDir.isDirectory()) continue;
    processTaskAttestation(
      taskDir,
      attestationRoot,
      sprintNumber,
      repoRoot,
      expectedSprintByTaskId,
      byTaskId,
      duplicateBuckets,
      sourceFiles
    );
  }
}

function loadCanonicalAttestations(
  specifySprintsDir: string,
  repoRoot: string,
  expectedSprintByTaskId: Map<string, number | 'Continuous'>
): {
  byTaskId: Map<string, NormalizedAttestation>;
  duplicateCanonicalAttestations: Array<{
    taskId: string;
    kept: string;
    skipped: string[];
  }>;
  ignoredSpecifySprintDirs: string[];
  sourceFiles: string[];
} {
  const byTaskId = new Map<string, NormalizedAttestation>();
  const duplicateBuckets = new Map<string, string[]>();
  const ignoredSpecifySprintDirs: string[] = [];
  const sourceFiles: string[] = [];

  if (!existsSync(specifySprintsDir)) {
    return { byTaskId, duplicateCanonicalAttestations: [], ignoredSpecifySprintDirs, sourceFiles };
  }

  for (const sprintDir of readdirSync(specifySprintsDir, { withFileTypes: true })) {
    processSprintAttestations(
      sprintDir,
      specifySprintsDir,
      repoRoot,
      expectedSprintByTaskId,
      byTaskId,
      duplicateBuckets,
      ignoredSpecifySprintDirs,
      sourceFiles
    );
  }

  const duplicateCanonicalAttestations = [...duplicateBuckets.entries()].map(([taskId, paths]) => {
    const kept = byTaskId.get(taskId);
    const keptRelative = kept ? toRepoRelative(repoRoot, kept.path) : paths[0]!;
    return {
      taskId,
      kept: keptRelative,
      skipped: paths.filter((path) => path !== keptRelative),
    };
  });

  return { byTaskId, duplicateCanonicalAttestations, ignoredSpecifySprintDirs, sourceFiles };
}

function summarizeDefinitionOfDone(
  items: NormalizedDoDItem[],
  fallbackDefinition: string
): string {
  if (items.length === 0) return summarizeText(normalizeDefinitionOfDoneText(fallbackDefinition), 240);

  const criteria = items
    .map((item) => item.criterion)
    .filter(Boolean)
    .slice(0, 3)
    .join('; ');

  return summarizeText(normalizeDefinitionOfDoneText(criteria), 240);
}

function summarizeTask(
  row: CsvTaskRow,
  attestation: NormalizedAttestation | undefined
): {
  title: string;
  summary: string;
  definitionOfDoneSnapshot: string;
  validationSummary: ValidationSummary;
  kpiSummary: KpiSummary;
} {
  const title = attestation?.title || normalizeWhitespace(row.Description);
  const definitionOfDoneSnapshot = summarizeDefinitionOfDone(
    attestation?.definitionOfDoneItems ?? [],
    row['Definition of Done']
  );
  const validationSummary = attestation?.validationSummary ?? {
    total: 0,
    passed: 0,
    failed: 0,
    failingNames: [],
  };
  const kpiSummary = attestation?.kpiSummary ?? { total: 0, met: 0, missed: 0 };
  const noteSummary = attestation?.notes
    ? summarizeText(stripNarrativeBoilerplate(attestation.notes), 240)
    : '';
  const invariantSummary =
    attestation && attestation.invariants.length > 0
      ? summarizeText(attestation.invariants.slice(0, 3).join('; '), 220)
      : '';
  const blockerSummary =
    attestation?.blockerDescription && attestation.blockerDescription.length > 0
      ? summarizeText(`Blocked because ${stripNarrativeBoilerplate(attestation.blockerDescription)}`, 240)
      : '';

  const noteIsProcedural =
    /repair|re-attestation|attestation|stub|checkbox|lint error|sha256/i.test(noteSummary);
  const primaryNarrative = blockerSummary || (!noteSummary || noteIsProcedural ? invariantSummary || noteSummary : noteSummary);

  const fragments = [primaryNarrative, definitionOfDoneSnapshot]
    .filter(Boolean)
    .reduce<string[]>((acc, fragment) => {
      if (
        acc.some(
          (existing) =>
            existing === fragment ||
            existing.includes(fragment) ||
            fragment.includes(existing)
        )
      ) {
        return acc;
      }
      acc.push(fragment);
      return acc;
    }, []);
  const summary =
    fragments.length > 0
      ? summarizeText(fragments.join(' '), 260)
      : summarizeText(normalizeDefinitionOfDoneText(row['Definition of Done']), 260);

  return { title, summary, definitionOfDoneSnapshot, validationSummary, kpiSummary };
}

function buildTaskRecord(
  row: CsvTaskRow,
  attestation: NormalizedAttestation | undefined,
  repoRoot: string
): ReportTask {
  const sprint = /^\d+$/.test(row['Target Sprint']) ? Number(row['Target Sprint']) : 'Continuous';
  const normalized = summarizeTask(row, attestation);

  return {
    taskId: row['Task ID'],
    sprint,
    status: row.Status,
    section: normalizeWhitespace(row.Section),
    title: normalized.title,
    description: normalizeWhitespace(row.Description),
    summary: normalized.summary,
    definitionOfDone: normalizeWhitespace(row['Definition of Done']),
    definitionOfDoneSnapshot: normalized.definitionOfDoneSnapshot,
    dependencies: parseDependencies((row.Dependencies || '').replaceAll(';', ','))
      .map((dep) => dep.replace(/:(?:FS|BS|TS)$/i, '')),
    attestation: {
      exists: Boolean(attestation),
      path: attestation ? toRepoRelative(repoRoot, attestation.path) : null,
      verdict: attestation?.verdict ?? null,
      timestamp: attestation?.timestamp ?? null,
      sprintFolder: attestation?.sprintFolder ?? null,
    },
    validationSummary: normalized.validationSummary,
    kpiSummary: normalized.kpiSummary,
  };
}

function taskRichnessScore(task: ReportTask): number {
  let score = 0;
  if (task.attestation.exists) score += 2;
  if (task.attestation.verdict) score += 1;
  if (task.summary.length > 0) score += Math.min(4, Math.floor(task.summary.length / 80));
  score += Math.min(4, task.validationSummary.passed);
  score += Math.min(4, task.kpiSummary.met);
  score += task.definitionOfDoneSnapshot.includes('DoD items met') ? 2 : 0;
  return score;
}

function selectRepresentativeTasks(tasks: ReportTask[], limit: number): ReportTask[] {
  const sorted = [...tasks].sort((left, right) => {
    const scoreDiff = taskRichnessScore(right) - taskRichnessScore(left);
    if (scoreDiff !== 0) return scoreDiff;
    return left.taskId.localeCompare(right.taskId);
  });

  const selected: ReportTask[] = [];
  const seenSections = new Set<string>();

  for (const task of sorted) {
    if (selected.length >= limit) break;
    if (!seenSections.has(task.section) || selected.length + 2 >= limit) {
      selected.push(task);
      seenSections.add(task.section);
    }
  }

  for (const task of sorted) {
    if (selected.length >= limit) break;
    if (!selected.some((entry) => entry.taskId === task.taskId)) {
      selected.push(task);
    }
  }

  return selected;
}

function buildSprintContext(tasks: ReportTask[]): string {
  const sectionCounts = new Map<string, number>();
  for (const task of tasks) {
    sectionCounts.set(task.section, (sectionCounts.get(task.section) ?? 0) + 1);
  }

  const topSections = [...sectionCounts.entries()]
    .sort((left, right) => right[1] - left[1] || left[0].localeCompare(right[0]))
    .slice(0, 3)
    .map(([section, count]) => `${section} (${count})`);

  return topSections.length > 0
    ? `Primary focus areas: ${topSections.join(', ')}.`
    : 'Primary focus areas could not be derived from the current source data.';
}

function buildSectionSummary(tasks: ReportTask[]): SprintReport['sectionSummary'] {
  const counts = new Map<
    string,
    { section: string; total: number; completed: number; open: number }
  >();

  for (const task of tasks) {
    const current = counts.get(task.section) ?? {
      section: task.section,
      total: 0,
      completed: 0,
      open: 0,
    };
    current.total += 1;
    if (isCompletedStatus(task.status)) current.completed += 1;
    else current.open += 1;
    counts.set(task.section, current);
  }

  return [...counts.values()].sort(
    (left, right) => right.total - left.total || left.section.localeCompare(right.section)
  );
}

function buildSprintReports(
  sprintTasks: ReportTask[],
  sprintNames: Map<number, SprintNameEntry>,
  numericSprintIds: number[]
): SprintReport[] {
  return numericSprintIds.map((sprintNumber) => {
    const tasks = sprintTasks.filter((task) => task.sprint === sprintNumber);
    const completed = tasks.filter((task) => isCompletedStatus(task.status));
    const backlog = tasks.filter((task) => normalizeWhitespace(task.status) === 'Backlog');
    const blocked = tasks.filter((task) => normalizeWhitespace(task.status) === 'Blocked');
    const inProgress = tasks.filter((task) => normalizeWhitespace(task.status) === 'In Progress');
    const attestedCompleted = completed.filter((task) => task.attestation.exists);
    const sprintName = sprintNames.get(sprintNumber);
    const sectionSummary = buildSectionSummary(tasks);

    return {
      sprint: sprintNumber,
      name: sprintName?.name ?? `Sprint ${sprintNumber}`,
      summarySource: sprintName?.source ?? 'synthetic',
      totalTasks: tasks.length,
      completedTasks: completed.length,
      backlogTasks: backlog.length,
      blockedTasks: blocked.length,
      inProgressTasks: inProgress.length,
      attestedCompletedTasks: attestedCompleted.length,
      missingCompletedAttestations: completed
        .filter((task) => !task.attestation.exists)
        .map((task) => task.taskId),
      context: buildSprintContext(tasks),
      notableCompleted: selectRepresentativeTasks(completed, 5),
      openTasks: [...blocked, ...inProgress, ...backlog].slice(0, 5),
      sectionSummary,
      tasks,
    } satisfies SprintReport;
  });
}

function renderTaskBullet(task: ReportTask): string {
  return `- **${task.taskId}** — ${task.title}. ${task.summary}`;
}

function renderSprintSection(sprint: SprintReport): string {
  const inProgressSuffix = sprint.inProgressTasks > 0 ? `, ${sprint.inProgressTasks} in progress` : '';
  const lines: string[] = [
    `## Sprint ${sprint.sprint} - ${sprint.name}`,
    '',
    `- Status: ${sprint.completedTasks}/${sprint.totalTasks} completed, ${sprint.backlogTasks} backlog, ${sprint.blockedTasks} blocked${inProgressSuffix}.`,
    `- ${sprint.context}`,
    `- Evidence coverage: ${sprint.attestedCompletedTasks}/${sprint.completedTasks} completed tasks have canonical \`attestation.json\` evidence.`,
  ];

  if (sprint.missingCompletedAttestations.length > 0) {
    lines.push(
      `- Evidence gaps: completed in CSV but missing canonical attestation: ${sprint.missingCompletedAttestations.join(', ')}.`
    );
  }

  if (sprint.notableCompleted.length > 0) {
    lines.push('', '**Accomplished**');
    for (const task of sprint.notableCompleted) {
      lines.push(renderTaskBullet(task));
    }
  }

  if (sprint.openTasks.length > 0) {
    lines.push('', '**Open Work**');
    for (const task of sprint.openTasks) {
      lines.push(`- **${task.taskId}** — ${task.title}. ${task.definitionOfDoneSnapshot}`);
    }
  }

  lines.push('');
  return lines.join('\n');
}

function renderMarkdown(data: CurrentStateReportData): string {
  const numberedBacklog = data.sprints.reduce((sum, s) => sum + s.backlogTasks, 0);
  const numberedBlocked = data.sprints.reduce((sum, s) => sum + s.blockedTasks, 0);
  const numberedInProgress = data.sprints.reduce((sum, s) => sum + s.inProgressTasks, 0);
  const numberedCompleted = data.overview.totalNumberedSprintTasks - numberedBacklog - numberedBlocked - numberedInProgress;
  const lines: string[] = [
    '# Current State Report',
    `_Generated: ${data.generatedAt}_`,
    '',
    '> Built dynamically from `.specify/sprints/**/attestations/*/attestation.json` for task evidence, the canonical `Sprint_plan.csv` for task ownership and fallback DoD, and existing sprint summary files for sprint titles when available.',
    '',
    '## Current State',
    '',
    `- Numbered sprint scope: ${data.overview.numberedSprintCount} sprints (${data.overview.numberedSprintRange}) plus ${data.overview.continuousTaskCount} continuous tasks.`,
    `- Overall progress: ${data.overview.completedTasks}/${data.overview.totalTasks} tasks completed (${data.overview.completionPercentage}%), ${data.overview.backlogTasks} backlog, ${data.overview.blockedTasks} blocked, ${data.overview.inProgressTasks} in progress.`,
    `- Numbered sprint progress alone: ${numberedCompleted}/${data.overview.totalNumberedSprintTasks} tasks completed or attested inside numbered sprints.`,
  ];

  if (data.currentState.blockedTasks.length > 0) {
    const blockedList = data.currentState.blockedTasks.map((task) => `${task.taskId} (${task.title})`).join(', ');
    lines.push(
      `- Blocking issue: ${blockedList}.`
    );
  } else {
    lines.push('- Blocking issue: none currently marked `Blocked` in the sprint plan.');
  }

  if (data.currentState.readyToStart.length > 0) {
    const readyList = data.currentState.readyToStart
      .slice(0, 5)
      .map((task) => `${task.taskId} (Sprint ${task.sprint})`)
      .join(', ');
    lines.push(`- Ready-to-start work: ${readyList}.`);
  }

  if (data.currentState.activeFocusSprints.length > 0) {
    lines.push(
      `- Active focus band: Sprint${data.currentState.activeFocusSprints.length > 1 ? 's' : ''} ${data.currentState.activeFocusSprints.join(', ')} carry the earliest remaining backlog.`
    );
  }

  lines.push('', '## Source Health', '');

  if (data.inconsistencies.missingSpecifySprintSummaries.length > 0) {
    lines.push(
      `- Missing \`.specify\` sprint summaries for ${data.inconsistencies.missingSpecifySprintSummaries.length} numbered sprints: ${data.inconsistencies.missingSpecifySprintSummaries.join(', ')}.`
    );
  } else {
    lines.push('- `.specify` sprint summary coverage is complete for the numbered sprint set.');
  }

  if (data.inconsistencies.completedWithoutCanonicalAttestation.length > 0) {
    lines.push(
      `- CSV marks these tasks completed without a canonical attestation: ${data.inconsistencies.completedWithoutCanonicalAttestation.join(', ')}.`
    );
  }

  if (data.inconsistencies.attestedButNotCompletedInCsv.length > 0) {
    const attestedList = data.inconsistencies.attestedButNotCompletedInCsv.map((entry) => `${entry.taskId} (${entry.status})`).join(', ');
    lines.push(`- Attested but not completed in CSV: ${attestedList}.`);
  }

  if (data.inconsistencies.sprintMismatches.length > 0) {
    const mismatchList = data.inconsistencies.sprintMismatches.map((m) => `${m.taskId} (CSV sprint ${m.csvSprint}, attested in sprint ${m.attestationSprint})`).join(', ');
    lines.push(`- Sprint mismatches (attestation in different sprint than CSV Target Sprint): ${mismatchList}.`);
  }

  if (data.inconsistencies.ignoredSpecifySprintDirs.length > 0) {
    lines.push(
      `- Ignored stray sprint directories outside the active numeric sprint set: ${data.inconsistencies.ignoredSpecifySprintDirs.join(', ')}.`
    );
  }

  lines.push('', '## Continuous Work', '');
  for (const task of data.continuousTasks) {
    lines.push(renderTaskBullet(task));
  }

  lines.push('', '## Sprint Summaries', '');
  for (const sprint of data.sprints) {
    lines.push(renderSprintSection(sprint));
  }

  return `${lines.join('\n').trim()}\n`;
}

export function generateCurrentStateReport(
  metricsDir: string,
  specifySprintsDir: string,
  repoRoot: string
): CurrentStateReportResult {
  const generatedAt = new Date().toISOString();
  const csvLoad = loadSprintPlanRows(metricsDir, repoRoot);
  const sprintNamesLoad = loadSprintNames(metricsDir, specifySprintsDir, repoRoot);

  const expectedSprintByTaskId = new Map<string, number | 'Continuous'>();
  for (const row of csvLoad.rows) {
    const sprint =
      /^\d+$/.test(row['Target Sprint']) ? Number(row['Target Sprint']) : ('Continuous' as const);
    expectedSprintByTaskId.set(row['Task ID'], sprint);
  }

  const attestationLoad = loadCanonicalAttestations(
    specifySprintsDir,
    repoRoot,
    expectedSprintByTaskId
  );
  const sourceFiles = [
    ...csvLoad.sourceFiles,
    ...sprintNamesLoad.sourceFiles,
    ...attestationLoad.sourceFiles,
  ];

  const tasks = csvLoad.rows.map((row) =>
    buildTaskRecord(row, attestationLoad.byTaskId.get(row['Task ID']), repoRoot)
  );
  const numericTasks = tasks.filter((task): task is ReportTask & { sprint: number } =>
    typeof task.sprint === 'number'
  );
  const continuousTasks = tasks.filter((task) => task.sprint === 'Continuous');
  const numericSprintIds = [...new Set(numericTasks.map((task) => task.sprint))].sort(
    (left, right) => left - right
  );

  const sprintReports = buildSprintReports(numericTasks, sprintNamesLoad.names, numericSprintIds);
  const completedTasks = tasks.filter((task) => isCompletedStatus(task.status));
  const backlogTasks = tasks.filter((task) => normalizeWhitespace(task.status) === 'Backlog');
  const blockedTasks = tasks.filter((task) => normalizeWhitespace(task.status) === 'Blocked');
  const inProgressTasks = tasks.filter(
    (task) => normalizeWhitespace(task.status) === 'In Progress'
  );
  const knownTaskIds = new Set([
    ...completedTasks.map((t) => t.taskId),
    ...backlogTasks.map((t) => t.taskId),
    ...blockedTasks.map((t) => t.taskId),
    ...inProgressTasks.map((t) => t.taskId),
  ]);
  const otherTasks = tasks.filter((task) => !knownTaskIds.has(task.taskId));

  const completedSet = new Set(completedTasks.map((task) => task.taskId));
  const readyToStart = backlogTasks
    .filter((task) => task.dependencies.every((dependency) => completedSet.has(dependency)))
    .sort((left, right) => {
      const leftSprint = typeof left.sprint === 'number' ? left.sprint : Number.MAX_SAFE_INTEGER;
      const rightSprint = typeof right.sprint === 'number' ? right.sprint : Number.MAX_SAFE_INTEGER;
      if (leftSprint !== rightSprint) return leftSprint - rightSprint;
      return left.taskId.localeCompare(right.taskId);
    })
    .slice(0, 10);

  const summaryCoverage = new Set(
    [...sprintNamesLoad.names.entries()]
      .filter(([, entry]) => entry.source === 'specify')
      .map(([sprint]) => sprint)
  );

  const data: CurrentStateReportData = {
    generatedAt,
    sources: {
      metricsDir: toRepoRelative(repoRoot, metricsDir),
      specifySprintsDir: toRepoRelative(repoRoot, specifySprintsDir),
      csvFiles: csvLoad.csvFiles,
      sourceFiles,
    },
    overview: {
      numberedSprintCount: numericSprintIds.length,
      numberedSprintRange:
        numericSprintIds.length > 0
          ? `${numericSprintIds[0]}-${numericSprintIds[numericSprintIds.length - 1]}`
          : 'n/a',
      totalTasks: tasks.length,
      totalNumberedSprintTasks: numericTasks.length,
      continuousTaskCount: continuousTasks.length,
      completedTasks: completedTasks.length,
      backlogTasks: backlogTasks.length,
      blockedTasks: blockedTasks.length,
      completionPercentage:
        tasks.length > 0 ? Number(((completedTasks.length / tasks.length) * 100).toFixed(2)) : 0,
      inProgressTasks: inProgressTasks.length,
      otherTasks: otherTasks.length,
    },
    inconsistencies: {
      missingSpecifySprintSummaries: numericSprintIds.filter((sprint) => !summaryCoverage.has(sprint)),
      ignoredSpecifySprintDirs: attestationLoad.ignoredSpecifySprintDirs,
      completedWithoutCanonicalAttestation: completedTasks
        .filter((task) => !task.attestation.exists)
        .map((task) => task.taskId),
      attestedButNotCompletedInCsv: tasks
        .filter((task) => task.attestation.exists && !isCompletedStatus(task.status))
        .map((task) => ({
          taskId: task.taskId,
          status: task.status,
          sprint: task.sprint,
          attestationPath: task.attestation.path ?? '',
        })),
      duplicateCanonicalAttestations: attestationLoad.duplicateCanonicalAttestations,
      sprintMismatches: tasks
        .filter(
          (task) =>
            task.attestation.exists &&
            typeof task.sprint === 'number' &&
            task.attestation.sprintFolder !== null &&
            task.attestation.sprintFolder !== task.sprint
        )
        .map((task) => ({
          taskId: task.taskId,
          csvSprint: task.sprint as number,
          attestationSprint: task.attestation.sprintFolder!,
        })),
    },
    continuousTasks,
    currentState: {
      blockedTasks,
      readyToStart,
      activeFocusSprints: sprintReports
        .filter((sprint) => sprint.backlogTasks > 0 || sprint.blockedTasks > 0 || sprint.inProgressTasks > 0)
        .slice(0, 4)
        .map((sprint) => sprint.sprint),
    },
    sprints: sprintReports,
  };

  return { markdown: renderMarkdown(data), data };
}
