# GitGuardian configuration
# https://docs.gitguardian.com/internal-repositories-monitoring/integrations/git_hooks/pre_commit

version: 2

# Paths to exclude from GitGuardian scanning
paths-ignore:
  # Test files and directories
  - "**/*.test.ts"
  - "**/*.test.tsx"
  - "**/*.test.js"
  - "**/*.test.jsx"
  - "**/*.spec.ts"
  - "**/*.spec.tsx"
  - "**/*.spec.js"
  - "**/*.spec.jsx"
  - "**/tests/**"
  - "**/test/**"
  - "**/__tests__/**"
  - "**/fixtures/**"
  - "**/mocks/**"
  
  # Storybook files (contain example/demo data)
  - "**/*.stories.ts"
  - "**/*.stories.tsx"
  - "**/*.stories.js"
  - "**/*.stories.jsx"
  
  # Test integration/e2e directories
  - "tests/**"
  - "e2e/**"
  
  # Example and documentation files
  - "**/*.example.*"
  - "**/examples/**"
  - "**/docs/**"
  
  # Build outputs and dependencies
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - ".next/**"
  - "out/**"
  - "coverage/**"

# Allow specific patterns that are false positives
# This is useful for test fixtures that look like secrets but aren't
exclude:
  # Test JWT tokens
  - name: "Test JWT tokens"
    match: "eyJ[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+\\.[A-Za-z0-9_-]+"
    paths:
      - "**/*.test.*"
      - "**/tests/**"
      - "**/__tests__/**"
  
  # Test passwords
  - name: "Test passwords"
    match: "(password|Password|PASSWORD)"
    paths:
      - "**/*.test.*"
      - "**/tests/**"
      - "**/__tests__/**"
      - "**/*.stories.*"
  
  # Generic high entropy in test/story files
  - name: "Test/Story high entropy strings"
    match: ".*"
    paths:
      - "**/*.test.*"
      - "**/*.stories.*"
      - "**/fixtures/**"
      - "**/mocks/**"
