/**
 * AutoResponseService Tests
 *
 * Tests the AutoResponseService application service which orchestrates
 * the auto-response workflow including draft creation, approval,
 * escalation, and send tracking.
 *
 * Coverage target: >90% for application layer
 */

import { describe, it, expect, beforeEach, vi } from 'vitest';
import {
  AutoResponseService,
  CreateAutoResponseProps,
  ApproveAutoResponseProps,
} from '../AutoResponseService';
import { Result, DomainError } from '@intelliflow/domain';

// Valid UUIDs for AutoResponseDraftId.fromString() which validates UUID format
const DRAFT_ID_1 = '00000000-0000-4000-8000-000000000001';
const DRAFT_ID_2 = '00000000-0000-4000-8000-000000000002';
const MISSING_ID = '00000000-0000-4000-8000-000000000099';

// ---------------------------------------------------------------------------
// Mock domain objects
// ---------------------------------------------------------------------------

/**
 * We mock the AutoResponseDraft aggregate since the service delegates
 * domain logic to it. This test focuses on the service's orchestration:
 * repository calls, event publishing, and error handling.
 */

function createMockDraft(overrides: Record<string, any> = {}): Record<string, any> {
  return {
    id: { toString: () => overrides.id ?? DRAFT_ID_1 },
    leadId: overrides.leadId ?? 'lead-1',
    content: { subject: 'Hello', body: 'World' },
    status: overrides.status ?? 'DRAFT',
    aiConfidence: overrides.aiConfidence ?? 0.85,
    triggerType: overrides.triggerType ?? 'EMAIL_RECEIVED',
    createdAt: new Date('2025-01-01'),
    expiresAt: new Date('2025-01-02'),
    recipientEmail: 'lead@example.com',
    modelVersion: 'gpt-4-v1',
    statusHistory: [{ status: 'DRAFT', changedAt: new Date('2025-01-01'), reason: 'Generated by AI' }],
    approvalDecision: null,
    escalation: null,
    escalationCount: 0,
    submitForApproval: vi.fn().mockReturnValue(Result.ok(undefined)),
    approve: vi.fn().mockReturnValue(Result.ok(undefined)),
    reject: vi.fn().mockReturnValue(Result.ok(undefined)),
    escalate: vi.fn().mockReturnValue(Result.ok(undefined)),
    resolveEscalation: vi.fn().mockReturnValue(Result.ok(undefined)),
    markSent: vi.fn().mockReturnValue(Result.ok(undefined)),
    markSendFailed: vi.fn().mockReturnValue(Result.ok(undefined)),
    invalidate: vi.fn(),
    checkExpiry: vi.fn().mockReturnValue(false),
    getDomainEvents: vi.fn().mockReturnValue([]),
    clearDomainEvents: vi.fn(),
    ...overrides,
  };
}

// ---------------------------------------------------------------------------
// Mock factories
// ---------------------------------------------------------------------------

function createMockDraftRepository(): Record<string, any> {
  return {
    save: vi.fn().mockResolvedValue(undefined),
    findById: vi.fn(),
    find: vi.fn(),
    findActiveByLeadAndTrigger: vi.fn(),
    findPendingForApprover: vi.fn(),
    findPendingByLeadId: vi.fn(),
    findExpired: vi.fn(),
    delete: vi.fn(),
    countByStatus: vi.fn(),
  };
}

function createMockEventBus(): Record<string, any> {
  return {
    publish: vi.fn().mockResolvedValue(undefined),
    publishAll: vi.fn().mockResolvedValue(undefined),
    subscribe: vi.fn().mockResolvedValue(undefined),
  };
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('AutoResponseService', () => {
  let service: AutoResponseService;
  let draftRepo: Record<string, any>;
  let eventBus: Record<string, any>;

  beforeEach(() => {
    draftRepo = createMockDraftRepository();
    eventBus = createMockEventBus();

    service = new AutoResponseService(draftRepo as any, eventBus as any);
  });

  // =========================================================================
  // create
  // =========================================================================

  describe('create', () => {
    const validProps: CreateAutoResponseProps = {
      tenantId: 'tenant-1',
      leadId: 'lead-1',
      leadTenantId: 'tenant-1',
      leadStatus: 'NEW',
      triggerType: 'EMAIL_RECEIVED',
      subject: 'Hello Lead',
      body: 'Thank you for your interest',
      aiConfidence: 0.85,
      modelVersion: 'gpt-4-v1',
      recipientEmail: 'lead@example.com',
    };

    it('should return failure if active draft exists for lead+trigger', async () => {
      draftRepo.findActiveByLeadAndTrigger.mockResolvedValue(createMockDraft());

      const result = await service.create(validProps);

      expect(result.isFailure).toBe(true);
      expect(result.error.message).toContain('Active draft already exists');
    });

    it('should return failure for invalid lead status', async () => {
      draftRepo.findActiveByLeadAndTrigger.mockResolvedValue(null);

      const result = await service.create({
        ...validProps,
        leadStatus: 'CLOSED',
      });

      // AutoResponseDraft.create returns fail for invalid status
      expect(result.isFailure).toBe(true);
    });

    it('should return failure for tenant mismatch', async () => {
      draftRepo.findActiveByLeadAndTrigger.mockResolvedValue(null);

      const result = await service.create({
        ...validProps,
        leadTenantId: 'different-tenant',
      });

      expect(result.isFailure).toBe(true);
    });

    it('should save draft and publish events on success', async () => {
      draftRepo.findActiveByLeadAndTrigger.mockResolvedValue(null);

      const result = await service.create(validProps);

      expect(result.isSuccess).toBe(true);
      expect(result.value.status).toBe('DRAFT');
      expect(result.value.aiConfidence).toBe(0.85);
      expect(draftRepo.save).toHaveBeenCalledTimes(1);
    });

    it('should return draftId in result', async () => {
      draftRepo.findActiveByLeadAndTrigger.mockResolvedValue(null);

      const result = await service.create(validProps);

      expect(result.isSuccess).toBe(true);
      expect(typeof result.value.draftId).toBe('string');
      expect(result.value.draftId.length).toBeGreaterThan(0);
    });

    it('should return failure when save fails', async () => {
      draftRepo.findActiveByLeadAndTrigger.mockResolvedValue(null);
      draftRepo.save.mockRejectedValue(new Error('DB error'));

      const result = await service.create(validProps);

      expect(result.isFailure).toBe(true);
      expect(result.error.message).toContain('Failed to save auto-response draft');
    });

    it('should return failure for invalid content (empty subject)', async () => {
      draftRepo.findActiveByLeadAndTrigger.mockResolvedValue(null);

      const result = await service.create({
        ...validProps,
        subject: '',
      });

      expect(result.isFailure).toBe(true);
    });
  });

  // =========================================================================
  // getById
  // =========================================================================

  describe('getById', () => {
    it('should return draft details when found', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.getById(DRAFT_ID_1, 'tenant-1');

      expect(result.isSuccess).toBe(true);
      expect(result.value.id).toBe(DRAFT_ID_1);
      expect(result.value.subject).toBe('Hello');
      expect(result.value.body).toBe('World');
    });

    it('should return failure when draft not found', async () => {
      draftRepo.findById.mockResolvedValue(null);

      const result = await service.getById(MISSING_ID, 'tenant-1');

      expect(result.isFailure).toBe(true);
      expect(result.error.message).toContain('Draft not found');
    });
  });

  // =========================================================================
  // list
  // =========================================================================

  describe('list', () => {
    it('should return list of draft summaries', async () => {
      draftRepo.find.mockResolvedValue([createMockDraft(), createMockDraft({ id: DRAFT_ID_2 })]);

      const result = await service.list('tenant-1');

      expect(result.drafts).toHaveLength(2);
      expect(result.total).toBe(2);
    });

    it('should apply default limit and offset', async () => {
      draftRepo.find.mockResolvedValue([]);

      await service.list('tenant-1');

      const query = draftRepo.find.mock.calls[0][0];
      expect(query.limit).toBe(50);
      expect(query.offset).toBe(0);
    });

    it('should pass filter options', async () => {
      draftRepo.find.mockResolvedValue([]);

      await service.list('tenant-1', {
        leadId: 'lead-1',
        status: 'PENDING_APPROVAL',
        triggerType: 'EMAIL_RECEIVED',
        limit: 10,
        offset: 5,
      });

      const query = draftRepo.find.mock.calls[0][0];
      expect(query.tenantId).toBe('tenant-1');
      expect(query.leadId).toBe('lead-1');
      expect(query.status).toBe('PENDING_APPROVAL');
      expect(query.triggerType).toBe('EMAIL_RECEIVED');
      expect(query.limit).toBe(10);
      expect(query.offset).toBe(5);
    });

    it('should handle empty options', async () => {
      draftRepo.find.mockResolvedValue([]);

      await service.list('tenant-1', {});

      const query = draftRepo.find.mock.calls[0][0];
      expect(query.tenantId).toBe('tenant-1');
    });
  });

  // =========================================================================
  // submitForApproval
  // =========================================================================

  describe('submitForApproval', () => {
    it('should submit draft for approval', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.submitForApproval(DRAFT_ID_1, 'tenant-1', 'approver-1');

      expect(result.isSuccess).toBe(true);
      expect(mockDraft.submitForApproval).toHaveBeenCalledWith('approver-1');
      expect(draftRepo.save).toHaveBeenCalledWith(mockDraft);
    });

    it('should return failure when draft not found', async () => {
      draftRepo.findById.mockResolvedValue(null);

      const result = await service.submitForApproval(MISSING_ID, 'tenant-1', 'approver-1');

      expect(result.isFailure).toBe(true);
      expect(result.error.message).toContain('Draft not found');
    });

    it('should return failure when domain rejects submission', async () => {
      const mockDraft = createMockDraft();
      mockDraft.submitForApproval.mockReturnValue(
        Result.fail({ message: 'Invalid transition', code: 'INVALID_STATUS' } as any),
      );
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.submitForApproval(DRAFT_ID_1, 'tenant-1', 'approver-1');

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when save fails', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);
      draftRepo.save.mockRejectedValue(new Error('DB error'));

      const result = await service.submitForApproval(DRAFT_ID_1, 'tenant-1', 'approver-1');

      expect(result.isFailure).toBe(true);
      expect(result.error.message).toContain('Failed to save draft');
    });
  });

  // =========================================================================
  // approve
  // =========================================================================

  describe('approve', () => {
    it('should approve a draft', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);

      const props: ApproveAutoResponseProps = {
        draftId: DRAFT_ID_1,
        tenantId: 'tenant-1',
        approvedBy: 'reviewer-1',
        reason: 'Looks good',
      };

      const result = await service.approve(props);

      expect(result.isSuccess).toBe(true);
      expect(mockDraft.approve).toHaveBeenCalledWith('reviewer-1', undefined, 'Looks good');
    });

    it('should pass modifications to domain', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);

      await service.approve({
        draftId: DRAFT_ID_1,
        tenantId: 'tenant-1',
        approvedBy: 'reviewer-1',
        modifications: { subject: 'New Subject' },
      });

      expect(mockDraft.approve).toHaveBeenCalledWith(
        'reviewer-1',
        { subject: 'New Subject' },
        undefined,
      );
    });

    it('should return failure when draft not found', async () => {
      draftRepo.findById.mockResolvedValue(null);

      const result = await service.approve({
        draftId: MISSING_ID,
        tenantId: 'tenant-1',
        approvedBy: 'reviewer-1',
      });

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when domain rejects approval', async () => {
      const mockDraft = createMockDraft();
      mockDraft.approve.mockReturnValue(
        Result.fail({ message: 'Not pending approval', code: 'INVALID' } as any),
      );
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.approve({
        draftId: DRAFT_ID_1,
        tenantId: 'tenant-1',
        approvedBy: 'reviewer-1',
      });

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when save fails', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);
      draftRepo.save.mockRejectedValue(new Error('DB error'));

      const result = await service.approve({
        draftId: DRAFT_ID_1,
        tenantId: 'tenant-1',
        approvedBy: 'reviewer-1',
      });

      expect(result.isFailure).toBe(true);
    });
  });

  // =========================================================================
  // reject
  // =========================================================================

  describe('reject', () => {
    it('should reject a draft', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.reject(DRAFT_ID_1, 'tenant-1', 'reviewer-1', 'Not appropriate');

      expect(result.isSuccess).toBe(true);
      expect(mockDraft.reject).toHaveBeenCalledWith('reviewer-1', 'Not appropriate');
    });

    it('should return failure when draft not found', async () => {
      draftRepo.findById.mockResolvedValue(null);

      const result = await service.reject(MISSING_ID, 'tenant-1', 'reviewer-1', 'reason');

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when domain rejects rejection', async () => {
      const mockDraft = createMockDraft();
      mockDraft.reject.mockReturnValue(
        Result.fail({ message: 'Already rejected', code: 'INVALID' } as any),
      );
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.reject(DRAFT_ID_1, 'tenant-1', 'reviewer-1', 'reason');

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when save fails', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);
      draftRepo.save.mockRejectedValue(new Error('DB error'));

      const result = await service.reject(DRAFT_ID_1, 'tenant-1', 'reviewer-1', 'reason');

      expect(result.isFailure).toBe(true);
    });
  });

  // =========================================================================
  // escalate
  // =========================================================================

  describe('escalate', () => {
    it('should escalate a draft', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.escalate(
        DRAFT_ID_1, 'tenant-1', 'user-1', 'manager-1', 'Need review', 48,
      );

      expect(result.isSuccess).toBe(true);
      expect(mockDraft.escalate).toHaveBeenCalledWith('user-1', 'manager-1', 'Need review', 48);
    });

    it('should return failure when draft not found', async () => {
      draftRepo.findById.mockResolvedValue(null);

      const result = await service.escalate(
        MISSING_ID, 'tenant-1', 'user-1', 'manager-1', 'reason',
      );

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when domain rejects escalation', async () => {
      const mockDraft = createMockDraft();
      mockDraft.escalate.mockReturnValue(
        Result.fail({ message: 'Max escalations reached', code: 'MAX' } as any),
      );
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.escalate(
        DRAFT_ID_1, 'tenant-1', 'user-1', 'manager-1', 'reason',
      );

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when save fails', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);
      draftRepo.save.mockRejectedValue(new Error('DB error'));

      const result = await service.escalate(
        DRAFT_ID_1, 'tenant-1', 'user-1', 'manager-1', 'reason',
      );

      expect(result.isFailure).toBe(true);
    });
  });

  // =========================================================================
  // resolveEscalation
  // =========================================================================

  describe('resolveEscalation', () => {
    it('should resolve an escalation', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.resolveEscalation(
        DRAFT_ID_1, 'tenant-1', 'manager-1', 'All good',
      );

      expect(result.isSuccess).toBe(true);
      expect(mockDraft.resolveEscalation).toHaveBeenCalledWith('manager-1', 'All good');
    });

    it('should return failure when draft not found', async () => {
      draftRepo.findById.mockResolvedValue(null);

      const result = await service.resolveEscalation(MISSING_ID, 'tenant-1', 'manager-1');

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when domain rejects resolution', async () => {
      const mockDraft = createMockDraft();
      mockDraft.resolveEscalation.mockReturnValue(
        Result.fail({ message: 'Not escalated', code: 'INVALID' } as any),
      );
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.resolveEscalation(DRAFT_ID_1, 'tenant-1', 'manager-1');

      expect(result.isFailure).toBe(true);
    });
  });

  // =========================================================================
  // markSent
  // =========================================================================

  describe('markSent', () => {
    it('should mark draft as sent', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.markSent(DRAFT_ID_1, 'tenant-1', 'notif-123');

      expect(result.isSuccess).toBe(true);
      expect(mockDraft.markSent).toHaveBeenCalledWith('notif-123');
    });

    it('should return failure when draft not found', async () => {
      draftRepo.findById.mockResolvedValue(null);

      const result = await service.markSent(MISSING_ID, 'tenant-1', 'notif-123');

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when domain rejects', async () => {
      const mockDraft = createMockDraft();
      mockDraft.markSent.mockReturnValue(
        Result.fail({ message: 'Not approved', code: 'INVALID' } as any),
      );
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.markSent(DRAFT_ID_1, 'tenant-1', 'notif-123');

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when save fails', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);
      draftRepo.save.mockRejectedValue(new Error('DB error'));

      const result = await service.markSent(DRAFT_ID_1, 'tenant-1', 'notif-123');

      expect(result.isFailure).toBe(true);
    });
  });

  // =========================================================================
  // markFailed
  // =========================================================================

  describe('markFailed', () => {
    it('should mark draft as failed', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.markFailed(DRAFT_ID_1, 'tenant-1', 'SMTP timeout');

      expect(result.isSuccess).toBe(true);
      expect(mockDraft.markSendFailed).toHaveBeenCalledWith('SMTP timeout');
    });

    it('should return failure when draft not found', async () => {
      draftRepo.findById.mockResolvedValue(null);

      const result = await service.markFailed(MISSING_ID, 'tenant-1', 'error');

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when domain rejects', async () => {
      const mockDraft = createMockDraft();
      mockDraft.markSendFailed.mockReturnValue(
        Result.fail({ message: 'Not in sendable state', code: 'INVALID' } as any),
      );
      draftRepo.findById.mockResolvedValue(mockDraft);

      const result = await service.markFailed(DRAFT_ID_1, 'tenant-1', 'error');

      expect(result.isFailure).toBe(true);
    });

    it('should return failure when save fails', async () => {
      const mockDraft = createMockDraft();
      draftRepo.findById.mockResolvedValue(mockDraft);
      draftRepo.save.mockRejectedValue(new Error('DB error'));

      const result = await service.markFailed(DRAFT_ID_1, 'tenant-1', 'error');

      expect(result.isFailure).toBe(true);
    });
  });

  // =========================================================================
  // getPendingForApprover
  // =========================================================================

  describe('getPendingForApprover', () => {
    it('should return pending drafts as summaries', async () => {
      draftRepo.findPendingForApprover.mockResolvedValue([
        createMockDraft({ id: 'draft-1' }),
        createMockDraft({ id: 'draft-2' }),
      ]);

      const result = await service.getPendingForApprover('approver-1', 'tenant-1');

      expect(result).toHaveLength(2);
      expect(result[0].id).toBe('draft-1');
      expect(result[0]).toHaveProperty('subject');
      expect(result[0]).toHaveProperty('status');
      expect(result[0]).toHaveProperty('aiConfidence');
    });
  });

  // =========================================================================
  // invalidatePendingByLead
  // =========================================================================

  describe('invalidatePendingByLead', () => {
    it('should invalidate all pending drafts for a lead', async () => {
      const draft1 = createMockDraft({ id: 'draft-1' });
      const draft2 = createMockDraft({ id: 'draft-2' });
      draftRepo.findPendingByLeadId.mockResolvedValue([draft1, draft2]);

      const count = await service.invalidatePendingByLead(
        'lead-1', 'tenant-1', 'Lead status changed',
      );

      expect(count).toBe(2);
      expect(draft1.invalidate).toHaveBeenCalledWith('Lead status changed');
      expect(draft2.invalidate).toHaveBeenCalledWith('Lead status changed');
      expect(draftRepo.save).toHaveBeenCalledTimes(2);
    });

    it('should continue processing if one draft fails to save', async () => {
      const draft1 = createMockDraft({ id: 'draft-1' });
      const draft2 = createMockDraft({ id: 'draft-2' });
      draftRepo.findPendingByLeadId.mockResolvedValue([draft1, draft2]);
      draftRepo.save
        .mockRejectedValueOnce(new Error('DB error'))
        .mockResolvedValueOnce(undefined);

      const count = await service.invalidatePendingByLead('lead-1', 'tenant-1', 'reason');

      // Only the second succeeds
      expect(count).toBe(1);
    });

    it('should return 0 when no pending drafts exist', async () => {
      draftRepo.findPendingByLeadId.mockResolvedValue([]);

      const count = await service.invalidatePendingByLead('lead-1', 'tenant-1', 'reason');

      expect(count).toBe(0);
    });
  });

  // =========================================================================
  // processExpiredDrafts
  // =========================================================================

  describe('processExpiredDrafts', () => {
    it('should process expired drafts', async () => {
      const draft1 = createMockDraft({ id: 'draft-1' });
      draft1.checkExpiry.mockReturnValue(true);
      const draft2 = createMockDraft({ id: 'draft-2' });
      draft2.checkExpiry.mockReturnValue(true);
      draftRepo.findExpired.mockResolvedValue([draft1, draft2]);

      const count = await service.processExpiredDrafts('tenant-1');

      expect(count).toBe(2);
      expect(draftRepo.save).toHaveBeenCalledTimes(2);
    });

    it('should skip drafts that are not actually expired', async () => {
      const draft1 = createMockDraft({ id: 'draft-1' });
      draft1.checkExpiry.mockReturnValue(false);
      draftRepo.findExpired.mockResolvedValue([draft1]);

      const count = await service.processExpiredDrafts('tenant-1');

      expect(count).toBe(0);
      expect(draftRepo.save).not.toHaveBeenCalled();
    });

    it('should continue processing if one draft fails', async () => {
      const draft1 = createMockDraft({ id: 'draft-1' });
      draft1.checkExpiry.mockReturnValue(true);
      const draft2 = createMockDraft({ id: 'draft-2' });
      draft2.checkExpiry.mockReturnValue(true);
      draftRepo.findExpired.mockResolvedValue([draft1, draft2]);
      draftRepo.save
        .mockRejectedValueOnce(new Error('DB error'))
        .mockResolvedValueOnce(undefined);

      const count = await service.processExpiredDrafts('tenant-1');

      expect(count).toBe(1);
    });

    it('should return 0 when no expired drafts exist', async () => {
      draftRepo.findExpired.mockResolvedValue([]);

      const count = await service.processExpiredDrafts('tenant-1');

      expect(count).toBe(0);
    });
  });

  // =========================================================================
  // getStatsByStatus
  // =========================================================================

  describe('getStatsByStatus', () => {
    it('should return counts for all statuses', async () => {
      draftRepo.countByStatus.mockResolvedValue(5);

      const stats = await service.getStatsByStatus('tenant-1');

      expect(stats.DRAFT).toBe(5);
      expect(stats.PENDING_APPROVAL).toBe(5);
      expect(stats.APPROVED).toBe(5);
      expect(stats.REJECTED).toBe(5);
      expect(stats.ESCALATED).toBe(5);
      expect(stats.SENT).toBe(5);
      expect(stats.FAILED).toBe(5);
      expect(stats.INVALIDATED).toBe(5);

      // Should call countByStatus for each status
      expect(draftRepo.countByStatus).toHaveBeenCalledTimes(8);
    });

    it('should pass tenantId and each status to repository', async () => {
      draftRepo.countByStatus.mockResolvedValue(0);

      await service.getStatsByStatus('tenant-1');

      const calls = draftRepo.countByStatus.mock.calls;
      const statuses = calls.map((c: any[]) => c[1]);
      expect(statuses).toContain('DRAFT');
      expect(statuses).toContain('PENDING_APPROVAL');
      expect(statuses).toContain('APPROVED');
      expect(statuses).toContain('REJECTED');
      expect(statuses).toContain('ESCALATED');
      expect(statuses).toContain('SENT');
      expect(statuses).toContain('FAILED');
      expect(statuses).toContain('INVALIDATED');

      // All calls should use tenant-1
      calls.forEach((c: any[]) => expect(c[0]).toBe('tenant-1'));
    });
  });

  // =========================================================================
  // Event publishing (private publishEvents)
  // =========================================================================

  describe('event publishing', () => {
    it('should publish events when draft has domain events', async () => {
      const mockEvent = { eventType: 'test.event' };
      const mockDraft = createMockDraft();
      mockDraft.getDomainEvents.mockReturnValue([mockEvent]);
      draftRepo.findById.mockResolvedValue(mockDraft);

      await service.submitForApproval(DRAFT_ID_1, 'tenant-1', 'approver-1');

      expect(eventBus.publishAll).toHaveBeenCalledWith([mockEvent]);
      expect(mockDraft.clearDomainEvents).toHaveBeenCalled();
    });

    it('should not publish when draft has no events', async () => {
      const mockDraft = createMockDraft();
      mockDraft.getDomainEvents.mockReturnValue([]);
      draftRepo.findById.mockResolvedValue(mockDraft);

      await service.submitForApproval(DRAFT_ID_1, 'tenant-1', 'approver-1');

      expect(eventBus.publishAll).not.toHaveBeenCalled();
      expect(mockDraft.clearDomainEvents).toHaveBeenCalled();
    });

    it('should handle event publishing failure gracefully', async () => {
      const mockDraft = createMockDraft();
      mockDraft.getDomainEvents.mockReturnValue([{ eventType: 'test' }]);
      draftRepo.findById.mockResolvedValue(mockDraft);
      eventBus.publishAll.mockRejectedValue(new Error('Event bus down'));

      // Should not throw - error is caught internally
      const result = await service.submitForApproval(DRAFT_ID_1, 'tenant-1', 'approver-1');

      expect(result.isSuccess).toBe(true);
      expect(mockDraft.clearDomainEvents).toHaveBeenCalled();
    });
  });
});
