-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public._prisma_migrations (
  id character varying NOT NULL,
  checksum character varying NOT NULL,
  finished_at timestamp with time zone,
  migration_name character varying NOT NULL,
  logs text,
  rolled_back_at timestamp with time zone,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  applied_steps_count integer NOT NULL DEFAULT 0,
  CONSTRAINT _prisma_migrations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.account_health_scores (
  id text NOT NULL,
  accountId text NOT NULL,
  accountName text NOT NULL,
  overallScore integer NOT NULL,
  usageScore integer,
  engagementScore integer,
  supportScore integer,
  paymentScore integer,
  churnRisk USER-DEFINED NOT NULL DEFAULT 'LOW'::"ChurnRisk",
  riskFactors jsonb,
  recommendations jsonb,
  calculatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  validUntil timestamp without time zone,
  tenantId text NOT NULL,
  CONSTRAINT account_health_scores_pkey PRIMARY KEY (id)
);
CREATE TABLE public.accounts (
  id text NOT NULL,
  name text NOT NULL,
  website text,
  industry text,
  employees integer,
  revenue numeric,
  description text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  ownerId text NOT NULL,
  parentAccountId text,
  CONSTRAINT accounts_pkey PRIMARY KEY (id),
  CONSTRAINT accounts_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT accounts_ownerId_fkey FOREIGN KEY (ownerId) REFERENCES public.users(id),
  CONSTRAINT accounts_parentAccountId_fkey FOREIGN KEY (parentAccountId) REFERENCES public.accounts(id)
);
CREATE TABLE public.activity_events (
  id text NOT NULL,
  type USER-DEFINED NOT NULL,
  title text NOT NULL,
  description text,
  timestamp timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  dateLabel text,
  attachmentName text,
  attachmentType text,
  stageFrom text,
  stageTo text,
  agentActionId text,
  agentName text,
  confidenceScore integer,
  agentStatus USER-DEFINED,
  opportunityId text,
  userId text,
  tenantId text NOT NULL,
  CONSTRAINT activity_events_pkey PRIMARY KEY (id),
  CONSTRAINT activity_events_opportunityId_fkey FOREIGN KEY (opportunityId) REFERENCES public.opportunities(id)
);
CREATE TABLE public.agent_actions (
  id text NOT NULL,
  actionType text NOT NULL,
  description text NOT NULL,
  aiReasoning text NOT NULL,
  confidenceScore integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING_APPROVAL'::"AgentActionStatus",
  entityId text NOT NULL,
  entityType text NOT NULL,
  entityName text NOT NULL,
  previousState jsonb NOT NULL,
  proposedState jsonb NOT NULL,
  agentId text NOT NULL,
  agentName text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiresAt timestamp without time zone NOT NULL,
  reviewedAt timestamp without time zone,
  reviewedBy text,
  feedback text,
  rolledBackAt timestamp without time zone,
  rolledBackBy text,
  rollbackReason text,
  tenantId text NOT NULL,
  CONSTRAINT agent_actions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_availability (
  id text NOT NULL,
  userId text NOT NULL,
  userName text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'OFFLINE'::"AgentStatus",
  statusMessage text,
  currentCapacity integer NOT NULL DEFAULT 0,
  maxCapacity integer NOT NULL DEFAULT 10,
  lastActiveAt timestamp without time zone,
  shiftStart timestamp without time zone,
  shiftEnd timestamp without time zone,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT agent_availability_pkey PRIMARY KEY (id)
);
CREATE TABLE public.agent_skills (
  id text NOT NULL,
  userId text NOT NULL,
  userName text NOT NULL,
  skillName text NOT NULL,
  proficiency integer NOT NULL,
  certified boolean NOT NULL DEFAULT false,
  certifiedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT agent_skills_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_insights (
  id text NOT NULL,
  type text NOT NULL,
  category text NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  confidence integer NOT NULL,
  priority text NOT NULL DEFAULT 'medium'::text,
  entityType text,
  entityId text,
  actionable boolean NOT NULL DEFAULT true,
  suggestedActions jsonb,
  metadata jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'NEW'::"InsightStatus",
  viewedAt timestamp without time zone,
  actedOnAt timestamp without time zone,
  dismissedAt timestamp without time zone,
  dismissReason text,
  expiresAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT ai_insights_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ai_output_review_audit (
  id text NOT NULL,
  reviewId text NOT NULL,
  eventType text NOT NULL,
  actorId text,
  actorType text NOT NULL DEFAULT 'USER'::text,
  metadata jsonb,
  timestamp timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT ai_output_review_audit_pkey PRIMARY KEY (id),
  CONSTRAINT ai_output_review_audit_reviewId_fkey FOREIGN KEY (reviewId) REFERENCES public.ai_output_reviews(id)
);
CREATE TABLE public.ai_output_reviews (
  id text NOT NULL,
  tenantId text NOT NULL,
  outputType USER-DEFINED NOT NULL,
  outputPayload jsonb NOT NULL,
  confidence double precision NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"ReviewStatus",
  slaDeadline timestamp without time zone NOT NULL,
  escalationDepth integer NOT NULL DEFAULT 0,
  lockedBy text,
  lockedAt timestamp without time zone,
  lockExpiresAt timestamp without time zone,
  reviewerId text,
  reviewDecision USER-DEFINED,
  reviewNotes text,
  version integer NOT NULL DEFAULT 1,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT ai_output_reviews_pkey PRIMARY KEY (id),
  CONSTRAINT ai_output_reviews_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.ai_scores (
  id text NOT NULL,
  score integer NOT NULL,
  confidence double precision NOT NULL,
  factors jsonb NOT NULL,
  modelVersion text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  leadId text NOT NULL,
  scoredById text NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT ai_scores_pkey PRIMARY KEY (id),
  CONSTRAINT ai_scores_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.leads(id),
  CONSTRAINT ai_scores_scoredById_fkey FOREIGN KEY (scoredById) REFERENCES public.users(id)
);
CREATE TABLE public.alert_incidents (
  id text NOT NULL,
  alertRuleId text,
  alertName text NOT NULL,
  severity text NOT NULL,
  source text NOT NULL,
  message text NOT NULL,
  details jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'FIRING'::"AlertStatus",
  acknowledgedBy text,
  acknowledgedAt timestamp without time zone,
  resolvedBy text,
  resolvedAt timestamp without time zone,
  firedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT alert_incidents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.api_keys (
  id text NOT NULL,
  name text NOT NULL,
  keyHash text NOT NULL,
  keyPrefix text NOT NULL,
  userId text NOT NULL,
  scopes jsonb NOT NULL,
  rateLimit integer NOT NULL DEFAULT 1000,
  isActive boolean NOT NULL DEFAULT true,
  expiresAt timestamp without time zone,
  lastUsedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT api_keys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.api_usage_records (
  id text NOT NULL,
  apiKeyId text NOT NULL,
  endpoint text NOT NULL,
  method text NOT NULL,
  statusCode integer NOT NULL,
  responseTime integer NOT NULL,
  requestSize integer,
  responseSize integer,
  ipAddress text,
  userAgent text,
  recordedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT api_usage_records_pkey PRIMARY KEY (id),
  CONSTRAINT api_usage_records_apiKeyId_fkey FOREIGN KEY (apiKeyId) REFERENCES public.api_keys(id)
);
CREATE TABLE public.api_versions (
  id text NOT NULL,
  version text NOT NULL,
  status text NOT NULL,
  releaseDate timestamp without time zone NOT NULL,
  deprecatedAt timestamp without time zone,
  sunsetDate timestamp without time zone,
  changelog text,
  breakingChanges jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT api_versions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.appointment_attendees (
  id text NOT NULL,
  appointmentId text NOT NULL,
  userId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT appointment_attendees_pkey PRIMARY KEY (id),
  CONSTRAINT appointment_attendees_appointmentId_fkey FOREIGN KEY (appointmentId) REFERENCES public.appointments(id)
);
CREATE TABLE public.appointment_cases (
  id text NOT NULL,
  appointmentId text NOT NULL,
  caseId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT appointment_cases_pkey PRIMARY KEY (id),
  CONSTRAINT appointment_cases_appointmentId_fkey FOREIGN KEY (appointmentId) REFERENCES public.appointments(id)
);
CREATE TABLE public.appointments (
  id text NOT NULL,
  title text NOT NULL,
  description text,
  startTime timestamp without time zone NOT NULL,
  endTime timestamp without time zone NOT NULL,
  appointmentType USER-DEFINED NOT NULL DEFAULT 'MEETING'::"AppointmentType",
  status USER-DEFINED NOT NULL DEFAULT 'SCHEDULED'::"AppointmentStatus",
  location text,
  notes text,
  bufferMinutesBefore integer NOT NULL DEFAULT 0,
  bufferMinutesAfter integer NOT NULL DEFAULT 0,
  recurrence jsonb,
  parentAppointmentId text,
  externalCalendarId text,
  reminderMinutes integer,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  cancelledAt timestamp without time zone,
  completedAt timestamp without time zone,
  cancellationReason text,
  tenantId text NOT NULL,
  organizerId text NOT NULL,
  CONSTRAINT appointments_pkey PRIMARY KEY (id),
  CONSTRAINT appointments_parentAppointmentId_fkey FOREIGN KEY (parentAppointmentId) REFERENCES public.appointments(id),
  CONSTRAINT appointments_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.audit_log_entries (
  id text NOT NULL,
  tenantId text NOT NULL,
  eventType text NOT NULL,
  eventVersion text NOT NULL DEFAULT 'v1'::text,
  eventId text NOT NULL,
  timestamp timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  actorType USER-DEFINED NOT NULL DEFAULT 'USER'::"ActorType",
  actorId text,
  actorEmail text,
  actorRole text,
  resourceType text NOT NULL,
  resourceId text NOT NULL,
  resourceName text,
  action USER-DEFINED NOT NULL,
  actionResult USER-DEFINED NOT NULL DEFAULT 'SUCCESS'::"ActionResult",
  actionReason text,
  beforeState jsonb,
  afterState jsonb,
  changedFields ARRAY,
  ipAddress text,
  userAgent text,
  requestId text,
  traceId text,
  sessionId text,
  dataClassification USER-DEFINED NOT NULL DEFAULT 'INTERNAL'::"DataClassification",
  retentionExpiresAt timestamp without time zone,
  requiredPermission text,
  permissionGranted boolean NOT NULL DEFAULT true,
  permissionDeniedReason text,
  metadata jsonb,
  CONSTRAINT audit_log_entries_pkey PRIMARY KEY (id),
  CONSTRAINT audit_log_entries_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT audit_log_entries_actorId_fkey FOREIGN KEY (actorId) REFERENCES public.users(id)
);
CREATE TABLE public.auto_response_drafts (
  id text NOT NULL,
  tenantId text NOT NULL,
  leadId text NOT NULL,
  recipientEmail text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  triggerType USER-DEFINED NOT NULL DEFAULT 'EMAIL_RECEIVED'::"AutoResponseTrigger",
  aiConfidence double precision NOT NULL,
  modelVersion text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::"AutoResponseStatus",
  version integer NOT NULL DEFAULT 0,
  expiresAt timestamp without time zone NOT NULL,
  statusHistory jsonb NOT NULL DEFAULT '[]'::jsonb,
  approvalDecision jsonb,
  escalation jsonb,
  escalationCount integer NOT NULL DEFAULT 0,
  sentAt timestamp without time zone,
  sendError text,
  messageId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT auto_response_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT auto_response_drafts_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT auto_response_drafts_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.leads(id)
);
CREATE TABLE public.business_rule_executions (
  id text NOT NULL,
  ruleId text NOT NULL,
  entityType text NOT NULL,
  entityId text NOT NULL,
  triggered boolean NOT NULL,
  conditionsMet jsonb,
  actionsExecuted jsonb,
  result text NOT NULL,
  error text,
  executedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT business_rule_executions_pkey PRIMARY KEY (id),
  CONSTRAINT business_rule_executions_ruleId_fkey FOREIGN KEY (ruleId) REFERENCES public.business_rules(id)
);
CREATE TABLE public.business_rules (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  entityType text NOT NULL,
  ruleType text NOT NULL,
  conditions jsonb NOT NULL,
  actions jsonb NOT NULL,
  priority integer NOT NULL DEFAULT 0,
  isActive boolean NOT NULL DEFAULT true,
  createdBy text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT business_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.calendar_events (
  id text NOT NULL,
  title text NOT NULL,
  description text,
  startTime timestamp without time zone NOT NULL,
  endTime timestamp without time zone,
  location text,
  eventType USER-DEFINED NOT NULL DEFAULT 'MEETING'::"CalendarEventType",
  attendees jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  contactId text,
  ownerId text,
  CONSTRAINT calendar_events_pkey PRIMARY KEY (id),
  CONSTRAINT calendar_events_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT calendar_events_contactId_fkey FOREIGN KEY (contactId) REFERENCES public.contacts(id)
);
CREATE TABLE public.call_records (
  id text NOT NULL,
  direction text NOT NULL,
  fromNumber text NOT NULL,
  toNumber text NOT NULL,
  contactId text,
  contactName text,
  userId text,
  userName text,
  duration integer NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'COMPLETED'::"CallStatus",
  outcome text,
  recordingUrl text,
  recordingDuration integer,
  transcription text,
  summary text,
  sentiment text,
  dealId text,
  ticketId text,
  notes text,
  startedAt timestamp without time zone NOT NULL,
  endedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT call_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.case_document_acl (
  id text NOT NULL,
  document_id text NOT NULL,
  tenant_id text NOT NULL,
  principal_id text NOT NULL,
  principal_type text NOT NULL,
  access_level text NOT NULL,
  granted_by text NOT NULL,
  granted_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expires_at timestamp without time zone,
  CONSTRAINT case_document_acl_pkey PRIMARY KEY (id),
  CONSTRAINT case_document_acl_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.case_documents(id)
);
CREATE TABLE public.case_document_audit (
  id text NOT NULL,
  document_id text NOT NULL,
  tenant_id text NOT NULL,
  event_type text NOT NULL,
  user_id text NOT NULL,
  ip_address text,
  user_agent text,
  changes jsonb,
  metadata jsonb,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT case_document_audit_pkey PRIMARY KEY (id),
  CONSTRAINT case_document_audit_document_id_fkey FOREIGN KEY (document_id) REFERENCES public.case_documents(id)
);
CREATE TABLE public.case_documents (
  id text NOT NULL,
  tenant_id text NOT NULL,
  version_major integer NOT NULL DEFAULT 1,
  version_minor integer NOT NULL DEFAULT 0,
  version_patch integer NOT NULL DEFAULT 0,
  parent_version_id text,
  is_latest_version boolean NOT NULL DEFAULT true,
  status text NOT NULL,
  title text NOT NULL,
  description text,
  document_type text NOT NULL,
  classification text NOT NULL,
  tags ARRAY DEFAULT ARRAY[]::text[],
  related_case_id text,
  related_contact_id text,
  storage_key text NOT NULL,
  content_hash text NOT NULL,
  mime_type text NOT NULL,
  size_bytes bigint NOT NULL,
  signed_by text,
  signed_at timestamp without time zone,
  signature_hash text,
  signature_ip_address text,
  signature_user_agent text,
  created_by text NOT NULL,
  created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by text NOT NULL,
  updated_at timestamp without time zone NOT NULL,
  retention_until timestamp without time zone,
  deleted_at timestamp without time zone,
  CONSTRAINT case_documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.case_tasks (
  id text NOT NULL,
  caseId text NOT NULL,
  title text NOT NULL,
  description text,
  dueDate timestamp without time zone,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"CaseTaskStatus",
  assignee text,
  completedAt timestamp without time zone,
  tenantId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT case_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT case_tasks_caseId_fkey FOREIGN KEY (caseId) REFERENCES public.cases(id),
  CONSTRAINT case_tasks_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.cases (
  id text NOT NULL,
  title text NOT NULL,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'OPEN'::"CaseStatus",
  priority USER-DEFINED NOT NULL DEFAULT 'MEDIUM'::"CasePriority",
  deadline timestamp without time zone,
  clientId text NOT NULL,
  assignedTo text NOT NULL,
  resolution text,
  parties jsonb,
  closedAt timestamp without time zone,
  tenantId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT cases_pkey PRIMARY KEY (id),
  CONSTRAINT cases_clientId_fkey FOREIGN KEY (clientId) REFERENCES public.accounts(id),
  CONSTRAINT cases_assignedTo_fkey FOREIGN KEY (assignedTo) REFERENCES public.users(id),
  CONSTRAINT cases_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.chain_version_audit (
  id text NOT NULL,
  versionId text NOT NULL,
  action text NOT NULL,
  previousStatus text,
  newStatus text NOT NULL,
  reason text,
  performedBy text NOT NULL,
  performedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  metadata jsonb,
  CONSTRAINT chain_version_audit_pkey PRIMARY KEY (id),
  CONSTRAINT chain_version_audit_versionId_fkey FOREIGN KEY (versionId) REFERENCES public.chain_versions(id)
);
CREATE TABLE public.chain_versions (
  id text NOT NULL,
  tenantId text NOT NULL,
  chainType text NOT NULL,
  version text NOT NULL,
  prompt text NOT NULL,
  promptHash text NOT NULL,
  model text NOT NULL DEFAULT 'gpt-4o-mini'::text,
  temperature double precision NOT NULL DEFAULT 0.7,
  maxTokens integer,
  config jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'DRAFT'::"ChainVersionStatus",
  rolloutStrategy USER-DEFINED NOT NULL DEFAULT 'IMMEDIATE'::"RolloutStrategy",
  rolloutPercent integer NOT NULL DEFAULT 100,
  experimentId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  createdBy text NOT NULL,
  activatedAt timestamp without time zone,
  activatedBy text,
  deprecatedAt timestamp without time zone,
  deprecatedBy text,
  archivedAt timestamp without time zone,
  description text,
  parentVersionId text,
  updatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT chain_versions_pkey PRIMARY KEY (id),
  CONSTRAINT chain_versions_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT chain_versions_parentVersionId_fkey FOREIGN KEY (parentVersionId) REFERENCES public.chain_versions(id)
);
CREATE TABLE public.chat_conversations (
  id text NOT NULL,
  channel USER-DEFINED NOT NULL DEFAULT 'INTERNAL'::"ChatChannel",
  externalId text,
  contactId text,
  contactName text,
  contactEmail text,
  subject text,
  status USER-DEFINED NOT NULL DEFAULT 'OPEN'::"ChatStatus",
  assigneeId text,
  priority text NOT NULL DEFAULT 'normal'::text,
  lastMessageAt timestamp without time zone,
  closedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT chat_conversations_pkey PRIMARY KEY (id)
);
CREATE TABLE public.chat_messages (
  id text NOT NULL,
  conversationId text NOT NULL,
  content text NOT NULL,
  senderType text NOT NULL,
  senderId text,
  senderName text NOT NULL,
  isRead boolean NOT NULL DEFAULT false,
  readAt timestamp without time zone,
  attachments jsonb,
  metadata jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_conversationId_fkey FOREIGN KEY (conversationId) REFERENCES public.chat_conversations(id)
);
CREATE TABLE public.contact_activities (
  id text NOT NULL,
  type USER-DEFINED NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  timestamp timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  userId text,
  userName text NOT NULL,
  sentiment USER-DEFINED,
  metadata jsonb,
  contactId text NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT contact_activities_pkey PRIMARY KEY (id),
  CONSTRAINT contact_activities_contactId_fkey FOREIGN KEY (contactId) REFERENCES public.contacts(id)
);
CREATE TABLE public.contact_ai_insights (
  id text NOT NULL,
  contactId text NOT NULL,
  conversionProbability integer NOT NULL,
  lifetimeValue integer NOT NULL,
  churnRisk USER-DEFINED NOT NULL DEFAULT 'LOW'::"ChurnRisk",
  nextBestAction text,
  sentiment text,
  engagementScore integer NOT NULL,
  recommendations jsonb,
  sentimentTrend text,
  lastEngagementDays integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT contact_ai_insights_pkey PRIMARY KEY (id),
  CONSTRAINT contact_ai_insights_contactId_fkey FOREIGN KEY (contactId) REFERENCES public.contacts(id)
);
CREATE TABLE public.contact_notes (
  id text NOT NULL,
  content text NOT NULL,
  author text NOT NULL,
  contactId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  embedding USER-DEFINED,
  search_vector tsvector,
  CONSTRAINT contact_notes_pkey PRIMARY KEY (id),
  CONSTRAINT contact_notes_contactId_fkey FOREIGN KEY (contactId) REFERENCES public.contacts(id),
  CONSTRAINT contact_notes_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.contacts (
  id text NOT NULL,
  email text NOT NULL,
  firstName text NOT NULL,
  lastName text NOT NULL,
  title text,
  phone text,
  department text,
  status USER-DEFINED NOT NULL DEFAULT 'ACTIVE'::"ContactStatus",
  streetAddress text,
  city text,
  zipCode text,
  company text,
  linkedInUrl text,
  contactType text,
  tags ARRAY DEFAULT ARRAY[]::text[],
  contactNotes text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  ownerId text NOT NULL,
  accountId text,
  leadId text,
  embedding USER-DEFINED,
  CONSTRAINT contacts_pkey PRIMARY KEY (id),
  CONSTRAINT contacts_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT contacts_ownerId_fkey FOREIGN KEY (ownerId) REFERENCES public.users(id),
  CONSTRAINT contacts_accountId_fkey FOREIGN KEY (accountId) REFERENCES public.accounts(id),
  CONSTRAINT contacts_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.leads(id)
);
CREATE TABLE public.conversation_records (
  id text NOT NULL,
  sessionId text NOT NULL,
  title text,
  summary text,
  contextName text,
  contextType text,
  contextId text,
  agentId text,
  agentName text,
  agentModel text,
  userName text,
  userAgent text,
  channel text NOT NULL DEFAULT 'web'::text,
  messageCount integer NOT NULL DEFAULT 0,
  toolCallCount integer NOT NULL DEFAULT 0,
  tokenCountInput integer,
  tokenCountOutput integer,
  status text NOT NULL DEFAULT 'ACTIVE'::text,
  startedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  endedAt timestamp without time zone,
  lastMessageAt timestamp without time zone,
  endReason text,
  userRating integer,
  feedbackText text,
  wasEscalated boolean NOT NULL DEFAULT false,
  escalatedTo text,
  escalatedAt timestamp without time zone,
  ipAddress text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  userId text NOT NULL,
  CONSTRAINT conversation_records_pkey PRIMARY KEY (id),
  CONSTRAINT conversation_records_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT conversation_records_userId_fkey FOREIGN KEY (userId) REFERENCES public.users(id)
);
CREATE TABLE public.dashboard_configs (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  userId text,
  isDefault boolean NOT NULL DEFAULT false,
  isShared boolean NOT NULL DEFAULT false,
  layout jsonb NOT NULL,
  widgets jsonb NOT NULL,
  filters jsonb,
  refreshInterval integer NOT NULL DEFAULT 300,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT dashboard_configs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.deal_files (
  id text NOT NULL,
  name text NOT NULL,
  size text NOT NULL,
  sizeBytes integer,
  fileType USER-DEFINED NOT NULL DEFAULT 'OTHER'::"FileType",
  url text,
  uploadedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  opportunityId text NOT NULL,
  uploadedById text,
  tenantId text NOT NULL,
  CONSTRAINT deal_files_pkey PRIMARY KEY (id),
  CONSTRAINT deal_files_opportunityId_fkey FOREIGN KEY (opportunityId) REFERENCES public.opportunities(id)
);
CREATE TABLE public.deal_products (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  quantity integer NOT NULL DEFAULT 1,
  unitPrice numeric NOT NULL,
  totalPrice numeric NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  opportunityId text NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT deal_products_pkey PRIMARY KEY (id),
  CONSTRAINT deal_products_opportunityId_fkey FOREIGN KEY (opportunityId) REFERENCES public.opportunities(id)
);
CREATE TABLE public.deal_renewals (
  id text NOT NULL,
  originalDealId text NOT NULL,
  renewalDealId text,
  renewalType text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'UPCOMING'::"RenewalStatus",
  renewalDate timestamp without time zone NOT NULL,
  notificationSentAt timestamp without time zone,
  value integer NOT NULL,
  previousValue integer,
  changePercent double precision,
  notes text,
  ownerId text NOT NULL,
  ownerName text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT deal_renewals_pkey PRIMARY KEY (id),
  CONSTRAINT deal_renewals_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.deals_won_metrics (
  id text NOT NULL,
  month text NOT NULL,
  year integer NOT NULL,
  value integer NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT deals_won_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.document_access_logs (
  id text NOT NULL,
  documentId text NOT NULL,
  userId text NOT NULL,
  userName text NOT NULL,
  action text NOT NULL,
  ipAddress text,
  userAgent text,
  accessedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT document_access_logs_pkey PRIMARY KEY (id),
  CONSTRAINT document_access_logs_documentId_fkey FOREIGN KEY (documentId) REFERENCES public.documents(id)
);
CREATE TABLE public.document_shares (
  id text NOT NULL,
  documentId text NOT NULL,
  sharedWith text NOT NULL,
  sharedBy text NOT NULL,
  permission text NOT NULL DEFAULT 'view'::text,
  expiresAt timestamp without time zone,
  accessedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT document_shares_pkey PRIMARY KEY (id),
  CONSTRAINT document_shares_documentId_fkey FOREIGN KEY (documentId) REFERENCES public.documents(id)
);
CREATE TABLE public.documents (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  fileName text NOT NULL,
  fileSize integer NOT NULL,
  fileType text NOT NULL,
  fileUrl text NOT NULL,
  category text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ACTIVE'::"DocumentStatus",
  version integer NOT NULL DEFAULT 1,
  parentId text,
  ocrContent text,
  metadata jsonb,
  uploadedBy text NOT NULL,
  uploadedByName text NOT NULL,
  contactId text,
  accountId text,
  dealId text,
  ticketId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT documents_pkey PRIMARY KEY (id)
);
CREATE TABLE public.domain_events (
  id text NOT NULL,
  eventType text NOT NULL,
  aggregateType text NOT NULL,
  aggregateId text NOT NULL,
  payload jsonb NOT NULL,
  metadata jsonb,
  occurredAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  processedAt timestamp without time zone,
  publishedAt timestamp without time zone,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"EventStatus",
  retryCount integer NOT NULL DEFAULT 0,
  nextRetryAt timestamp without time zone,
  lastError text,
  tenantId text NOT NULL,
  CONSTRAINT domain_events_pkey PRIMARY KEY (id),
  CONSTRAINT domain_events_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.email_attachments (
  id text NOT NULL,
  emailId text NOT NULL,
  fileName text NOT NULL,
  fileSize integer NOT NULL,
  fileType text NOT NULL,
  fileUrl text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT email_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT email_attachments_emailId_fkey FOREIGN KEY (emailId) REFERENCES public.email_records(id)
);
CREATE TABLE public.email_records (
  id text NOT NULL,
  templateId text,
  subject text NOT NULL,
  body text NOT NULL,
  fromEmail text NOT NULL,
  toEmail text NOT NULL,
  ccEmails text,
  bccEmails text,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"EmailStatus",
  sentAt timestamp without time zone,
  deliveredAt timestamp without time zone,
  openedAt timestamp without time zone,
  clickedAt timestamp without time zone,
  bouncedAt timestamp without time zone,
  openCount integer NOT NULL DEFAULT 0,
  clickCount integer NOT NULL DEFAULT 0,
  contactId text,
  dealId text,
  userId text,
  metadata jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  isRead boolean NOT NULL DEFAULT false,
  readAt timestamp without time zone,
  CONSTRAINT email_records_pkey PRIMARY KEY (id)
);
CREATE TABLE public.email_templates (
  id text NOT NULL,
  name text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  category text NOT NULL,
  isActive boolean NOT NULL DEFAULT true,
  variables jsonb,
  createdBy text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT email_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.escalation_history (
  id text NOT NULL,
  ticketId text NOT NULL,
  level integer NOT NULL,
  fromUserId text,
  fromUserName text,
  toUserId text NOT NULL,
  toUserName text NOT NULL,
  reason text NOT NULL,
  notes text,
  escalatedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  acknowledgedAt timestamp without time zone,
  resolvedAt timestamp without time zone,
  tenantId text NOT NULL,
  CONSTRAINT escalation_history_pkey PRIMARY KEY (id)
);
CREATE TABLE public.feedback_surveys (
  id text NOT NULL,
  type USER-DEFINED NOT NULL DEFAULT 'NPS'::"SurveyType",
  contactId text NOT NULL,
  contactName text NOT NULL,
  contactEmail text NOT NULL,
  ticketId text,
  dealId text,
  score integer CHECK (score IS NULL OR score >= 0 AND score <= 10),
  rating integer CHECK (rating IS NULL OR rating >= 1 AND rating <= 5),
  comment text,
  sentiment text,
  tags jsonb,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"FeedbackStatus",
  sentAt timestamp without time zone,
  respondedAt timestamp without time zone,
  followUpAt timestamp without time zone,
  followUpBy text,
  followUpNote text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT feedback_surveys_pkey PRIMARY KEY (id)
);
CREATE TABLE public.growth_metrics (
  id text NOT NULL,
  month text NOT NULL,
  year integer NOT NULL,
  value integer NOT NULL,
  metricType text NOT NULL DEFAULT 'revenue'::text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT growth_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.health_checks (
  id text NOT NULL,
  serviceName text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'HEALTHY'::"HealthStatus",
  responseTime integer,
  details jsonb,
  error text,
  checkedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT health_checks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.kpi_definitions (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  category text NOT NULL,
  metric text NOT NULL,
  calculation text NOT NULL,
  target double precision,
  unit text,
  format text,
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT kpi_definitions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lead_activities (
  id text NOT NULL,
  type USER-DEFINED NOT NULL,
  title text NOT NULL,
  description text NOT NULL,
  timestamp timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  userId text,
  userName text NOT NULL,
  sentiment USER-DEFINED,
  metadata jsonb,
  leadId text NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT lead_activities_pkey PRIMARY KEY (id),
  CONSTRAINT lead_activities_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.leads(id)
);
CREATE TABLE public.lead_ai_insights (
  id text NOT NULL,
  leadId text NOT NULL,
  conversionProbability integer NOT NULL,
  estimatedValue integer NOT NULL,
  churnRisk USER-DEFINED NOT NULL DEFAULT 'LOW'::"ChurnRisk",
  nextBestAction text,
  sentiment text,
  engagementScore integer NOT NULL,
  recommendations jsonb,
  sentimentTrend text,
  lastEngagementDays integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT lead_ai_insights_pkey PRIMARY KEY (id),
  CONSTRAINT lead_ai_insights_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.leads(id)
);
CREATE TABLE public.lead_conversion_audit (
  id text NOT NULL,
  leadId text NOT NULL,
  contactId text NOT NULL,
  accountId text,
  tenantId text NOT NULL,
  convertedBy text NOT NULL,
  conversionSnapshot jsonb NOT NULL,
  idempotencyKey text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT lead_conversion_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE public.lead_files (
  id text NOT NULL,
  name text NOT NULL,
  size text NOT NULL,
  sizeBytes integer,
  fileType USER-DEFINED NOT NULL DEFAULT 'OTHER'::"FileType",
  url text,
  uploadedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  leadId text NOT NULL,
  uploadedById text,
  tenantId text NOT NULL,
  CONSTRAINT lead_files_pkey PRIMARY KEY (id),
  CONSTRAINT lead_files_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.leads(id)
);
CREATE TABLE public.lead_notes (
  id text NOT NULL,
  content text NOT NULL,
  author text NOT NULL,
  leadId text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  embedding USER-DEFINED,
  search_vector tsvector,
  CONSTRAINT lead_notes_pkey PRIMARY KEY (id),
  CONSTRAINT lead_notes_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.leads(id)
);
CREATE TABLE public.leads (
  id text NOT NULL,
  email text NOT NULL,
  firstName text,
  lastName text,
  company text,
  title text,
  phone text,
  source USER-DEFINED NOT NULL DEFAULT 'WEBSITE'::"LeadSource",
  status USER-DEFINED NOT NULL DEFAULT 'NEW'::"LeadStatus",
  score integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  location text,
  website text,
  avatarUrl text,
  lastContactedAt timestamp without time zone,
  estimatedValue integer DEFAULT 0,
  tags ARRAY DEFAULT ARRAY[]::text[],
  tenantId text NOT NULL,
  ownerId text NOT NULL,
  embedding USER-DEFINED,
  CONSTRAINT leads_pkey PRIMARY KEY (id),
  CONSTRAINT leads_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT leads_ownerId_fkey FOREIGN KEY (ownerId) REFERENCES public.users(id)
);
CREATE TABLE public.message_records (
  id text NOT NULL,
  role text NOT NULL,
  content text NOT NULL,
  contentType text NOT NULL DEFAULT 'text'::text,
  metadata jsonb,
  attachments jsonb,
  modelUsed text,
  finishReason text,
  tokenCount integer,
  promptTokens integer,
  completionTokens integer,
  confidence double precision,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  conversationId text NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT message_records_pkey PRIMARY KEY (id),
  CONSTRAINT message_records_conversationId_fkey FOREIGN KEY (conversationId) REFERENCES public.conversation_records(id)
);
CREATE TABLE public.notification_delivery_logs (
  id text NOT NULL,
  notificationId text NOT NULL,
  attemptNumber integer NOT NULL,
  channel USER-DEFINED NOT NULL,
  status text NOT NULL,
  provider text,
  providerMessageId text,
  providerResponse jsonb,
  errorCode text,
  errorMessage text,
  attemptedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completedAt timestamp without time zone,
  durationMs integer,
  CONSTRAINT notification_delivery_logs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_dlq (
  id text NOT NULL,
  notificationId text NOT NULL,
  tenantId text NOT NULL,
  channel USER-DEFINED NOT NULL,
  recipientId text NOT NULL,
  subject text NOT NULL,
  body text NOT NULL,
  lastError text NOT NULL,
  retryCount integer NOT NULL,
  maxRetries integer NOT NULL DEFAULT 3,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"DLQStatus",
  resolvedAt timestamp without time zone,
  resolvedBy text,
  resolutionNote text,
  movedToDLQAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastRetryAt timestamp without time zone,
  CONSTRAINT notification_dlq_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_preferences (
  id text NOT NULL,
  tenantId text NOT NULL,
  userId text NOT NULL,
  channelPreferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  categoryPreferences jsonb NOT NULL DEFAULT '{}'::jsonb,
  quietHoursStart text NOT NULL DEFAULT '22:00'::text,
  quietHoursEnd text NOT NULL DEFAULT '08:00'::text,
  quietHoursEnabled boolean NOT NULL DEFAULT true,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  doNotDisturb boolean NOT NULL DEFAULT false,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT notification_preferences_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notification_templates (
  id text NOT NULL,
  tenantId text,
  name text NOT NULL,
  description text,
  channel USER-DEFINED NOT NULL,
  subject text NOT NULL,
  bodyText text NOT NULL,
  bodyHtml text,
  category USER-DEFINED NOT NULL DEFAULT 'SYSTEM'::"NotificationCategory",
  variables jsonb,
  version integer NOT NULL DEFAULT 1,
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT notification_templates_pkey PRIMARY KEY (id)
);
CREATE TABLE public.notifications (
  id text NOT NULL,
  tenantId text NOT NULL,
  recipientId text NOT NULL,
  recipientEmail text,
  recipientPhone text,
  channel USER-DEFINED NOT NULL DEFAULT 'IN_APP'::"NotificationChannel",
  subject text NOT NULL,
  body text NOT NULL,
  htmlBody text,
  templateId text,
  templateVariables jsonb,
  priority USER-DEFINED NOT NULL DEFAULT 'NORMAL'::"NotificationPriority",
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"NotificationStatus",
  category USER-DEFINED NOT NULL DEFAULT 'SYSTEM'::"NotificationCategory",
  providerMessageId text,
  error text,
  retryCount integer NOT NULL DEFAULT 0,
  scheduledAt timestamp without time zone,
  sentAt timestamp without time zone,
  deliveredAt timestamp without time zone,
  readAt timestamp without time zone,
  failedAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  metadata jsonb,
  sourceType text,
  sourceId text,
  CONSTRAINT notifications_pkey PRIMARY KEY (id)
);
CREATE TABLE public.opportunities (
  id text NOT NULL,
  name text NOT NULL,
  value numeric NOT NULL,
  stage USER-DEFINED NOT NULL DEFAULT 'PROSPECTING'::"OpportunityStage",
  probability integer NOT NULL DEFAULT 0,
  expectedCloseDate timestamp without time zone,
  description text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  closedAt timestamp without time zone,
  tenantId text NOT NULL,
  ownerId text NOT NULL,
  accountId text NOT NULL,
  contactId text,
  sourceLeadId text,
  CONSTRAINT opportunities_pkey PRIMARY KEY (id),
  CONSTRAINT opportunities_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT opportunities_ownerId_fkey FOREIGN KEY (ownerId) REFERENCES public.users(id),
  CONSTRAINT opportunities_accountId_fkey FOREIGN KEY (accountId) REFERENCES public.accounts(id),
  CONSTRAINT opportunities_contactId_fkey FOREIGN KEY (contactId) REFERENCES public.contacts(id)
);
CREATE TABLE public.performance_metrics (
  id text NOT NULL,
  metricName text NOT NULL,
  metricType text NOT NULL,
  value double precision NOT NULL,
  unit text,
  tags jsonb,
  serviceName text,
  recordedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT performance_metrics_pkey PRIMARY KEY (id)
);
CREATE TABLE public.permissions (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  resource text NOT NULL,
  action text NOT NULL,
  conditions jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT permissions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pipeline_snapshots (
  id text NOT NULL,
  stage text NOT NULL,
  value integer NOT NULL,
  dealCount integer NOT NULL,
  percentage integer NOT NULL,
  color text NOT NULL DEFAULT 'bg-ds-primary'::text,
  snapshotDate timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT pipeline_snapshots_pkey PRIMARY KEY (id)
);
CREATE TABLE public.pipeline_stage_configs (
  id text NOT NULL,
  stageKey text NOT NULL,
  displayName text NOT NULL,
  color text NOT NULL DEFAULT '#6366f1'::text,
  order integer NOT NULL,
  probability double precision NOT NULL DEFAULT 0,
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT pipeline_stage_configs_pkey PRIMARY KEY (id),
  CONSTRAINT pipeline_stage_configs_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.rbac_roles (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  level integer NOT NULL DEFAULT 0,
  isSystem boolean NOT NULL DEFAULT false,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT rbac_roles_pkey PRIMARY KEY (id)
);
CREATE TABLE public.related_tickets (
  id text NOT NULL,
  ticketId text NOT NULL,
  relatedId text NOT NULL,
  relatedSubject text NOT NULL,
  relatedStatus USER-DEFINED NOT NULL,
  similarity integer NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT related_tickets_pkey PRIMARY KEY (id),
  CONSTRAINT related_tickets_ticketId_fkey FOREIGN KEY (ticketId) REFERENCES public.tickets(id)
);
CREATE TABLE public.report_definitions (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  category text NOT NULL,
  type text NOT NULL,
  dataSource text NOT NULL,
  columns jsonb NOT NULL,
  filters jsonb,
  sorting jsonb,
  grouping jsonb,
  chartConfig jsonb,
  isPublic boolean NOT NULL DEFAULT false,
  createdBy text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT report_definitions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.report_executions (
  id text NOT NULL,
  reportId text NOT NULL,
  scheduleId text,
  triggeredBy text NOT NULL,
  status text NOT NULL,
  fileUrl text,
  fileSize integer,
  rowCount integer,
  executionTime integer,
  error text,
  startedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completedAt timestamp without time zone,
  tenantId text NOT NULL,
  CONSTRAINT report_executions_pkey PRIMARY KEY (id),
  CONSTRAINT report_executions_reportId_fkey FOREIGN KEY (reportId) REFERENCES public.report_definitions(id)
);
CREATE TABLE public.report_schedules (
  id text NOT NULL,
  reportId text NOT NULL,
  frequency text NOT NULL,
  dayOfWeek integer,
  dayOfMonth integer,
  timeOfDay text NOT NULL,
  timezone text NOT NULL DEFAULT 'UTC'::text,
  recipients jsonb NOT NULL,
  format text NOT NULL DEFAULT 'pdf'::text,
  isActive boolean NOT NULL DEFAULT true,
  lastRunAt timestamp without time zone,
  nextRunAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT report_schedules_pkey PRIMARY KEY (id),
  CONSTRAINT report_schedules_reportId_fkey FOREIGN KEY (reportId) REFERENCES public.report_definitions(id)
);
CREATE TABLE public.role_permissions (
  id text NOT NULL,
  roleId text NOT NULL,
  permissionId text NOT NULL,
  granted boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT role_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT role_permissions_roleId_fkey FOREIGN KEY (roleId) REFERENCES public.rbac_roles(id),
  CONSTRAINT role_permissions_permissionId_fkey FOREIGN KEY (permissionId) REFERENCES public.permissions(id)
);
CREATE TABLE public.routing_audits (
  id text NOT NULL,
  ticketId text NOT NULL,
  ruleId text,
  ruleName text,
  fromUserId text,
  fromUserName text,
  toUserId text NOT NULL,
  toUserName text NOT NULL,
  reason text NOT NULL,
  details jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT routing_audits_pkey PRIMARY KEY (id)
);
CREATE TABLE public.routing_rules (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  priority integer NOT NULL DEFAULT 0,
  isActive boolean NOT NULL DEFAULT true,
  conditions jsonb NOT NULL,
  actions jsonb NOT NULL,
  createdBy text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT routing_rules_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sales_performance (
  id text NOT NULL,
  userId text NOT NULL,
  userName text NOT NULL,
  userAvatar text,
  dealCount integer NOT NULL,
  revenue integer NOT NULL,
  rank integer NOT NULL,
  period text NOT NULL DEFAULT 'monthly'::text,
  snapshotDate timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT sales_performance_pkey PRIMARY KEY (id)
);
CREATE TABLE public.security_events (
  id text NOT NULL,
  eventType text NOT NULL,
  severity USER-DEFINED NOT NULL DEFAULT 'INFO'::"SecuritySeverity",
  tenantId text NOT NULL,
  actorId text,
  actorEmail text,
  actorIp text,
  description text,
  details jsonb,
  detected boolean NOT NULL DEFAULT false,
  detectedBy text,
  blocked boolean NOT NULL DEFAULT false,
  alertSent boolean NOT NULL DEFAULT false,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT security_events_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sla_breaches (
  id text NOT NULL,
  ticketId text NOT NULL,
  slaPolicyId text NOT NULL,
  breachType text NOT NULL,
  targetTime timestamp without time zone NOT NULL,
  breachedAt timestamp without time zone NOT NULL,
  durationOverdue integer NOT NULL,
  escalatedTo text,
  escalatedAt timestamp without time zone,
  resolved boolean NOT NULL DEFAULT false,
  resolvedAt timestamp without time zone,
  notes text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT sla_breaches_pkey PRIMARY KEY (id)
);
CREATE TABLE public.sla_notifications (
  id text NOT NULL,
  ticketId text NOT NULL,
  type USER-DEFINED NOT NULL,
  severity USER-DEFINED NOT NULL DEFAULT 'INFO'::"SLANotificationSeverity",
  message text NOT NULL,
  sentAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  acknowledgedAt timestamp without time zone,
  acknowledgedBy text,
  tenantId text NOT NULL,
  CONSTRAINT sla_notifications_pkey PRIMARY KEY (id),
  CONSTRAINT sla_notifications_ticketId_fkey FOREIGN KEY (ticketId) REFERENCES public.tickets(id)
);
CREATE TABLE public.sla_policies (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  criticalResponseMinutes integer NOT NULL DEFAULT 15,
  highResponseMinutes integer NOT NULL DEFAULT 60,
  mediumResponseMinutes integer NOT NULL DEFAULT 240,
  lowResponseMinutes integer NOT NULL DEFAULT 480,
  criticalResolutionMinutes integer NOT NULL DEFAULT 120,
  highResolutionMinutes integer NOT NULL DEFAULT 480,
  mediumResolutionMinutes integer NOT NULL DEFAULT 1440,
  lowResolutionMinutes integer NOT NULL DEFAULT 4320,
  warningThresholdPercent integer NOT NULL DEFAULT 25,
  isDefault boolean NOT NULL DEFAULT false,
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT sla_policies_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tasks (
  id text NOT NULL,
  title text NOT NULL,
  description text,
  dueDate timestamp without time zone,
  priority USER-DEFINED NOT NULL DEFAULT 'MEDIUM'::"TaskPriority",
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"TaskStatus",
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  completedAt timestamp without time zone,
  tenantId text NOT NULL,
  ownerId text NOT NULL,
  leadId text,
  contactId text,
  opportunityId text,
  CONSTRAINT tasks_pkey PRIMARY KEY (id),
  CONSTRAINT tasks_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT tasks_ownerId_fkey FOREIGN KEY (ownerId) REFERENCES public.users(id),
  CONSTRAINT tasks_leadId_fkey FOREIGN KEY (leadId) REFERENCES public.leads(id),
  CONSTRAINT tasks_contactId_fkey FOREIGN KEY (contactId) REFERENCES public.contacts(id),
  CONSTRAINT tasks_opportunityId_fkey FOREIGN KEY (opportunityId) REFERENCES public.opportunities(id)
);
CREATE TABLE public.team_members (
  id text NOT NULL,
  userId text NOT NULL,
  teamId text NOT NULL,
  role text NOT NULL DEFAULT 'member'::text,
  joinedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT team_members_pkey PRIMARY KEY (id),
  CONSTRAINT team_members_teamId_fkey FOREIGN KEY (teamId) REFERENCES public.teams(id)
);
CREATE TABLE public.team_messages (
  id text NOT NULL,
  userId text NOT NULL,
  userName text NOT NULL,
  userAvatar text,
  message text NOT NULL,
  channel text NOT NULL DEFAULT 'general'::text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT team_messages_pkey PRIMARY KEY (id)
);
CREATE TABLE public.teams (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  workspaceId text NOT NULL,
  leaderId text,
  isActive boolean NOT NULL DEFAULT true,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT teams_pkey PRIMARY KEY (id),
  CONSTRAINT teams_workspaceId_fkey FOREIGN KEY (workspaceId) REFERENCES public.workspaces(id)
);
CREATE TABLE public.tenant_modules (
  id text NOT NULL,
  tenantId text NOT NULL,
  moduleId USER-DEFINED NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  enabledAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  disabledAt timestamp without time zone,
  CONSTRAINT tenant_modules_pkey PRIMARY KEY (id),
  CONSTRAINT tenant_modules_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.tenants (
  id text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'ACTIVE'::"TenantStatus",
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT tenants_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ticket_activities (
  id text NOT NULL,
  type USER-DEFINED NOT NULL,
  content text NOT NULL,
  timestamp timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  isInternal boolean NOT NULL DEFAULT false,
  authorName text NOT NULL,
  authorRole text,
  authorAvatar text,
  channel USER-DEFINED NOT NULL DEFAULT 'PORTAL'::"TicketChannel",
  isAIGenerated boolean NOT NULL DEFAULT false,
  aiConfidence double precision,
  systemEventType text,
  systemEventData jsonb,
  tenantId text NOT NULL,
  ticketId text NOT NULL,
  CONSTRAINT ticket_activities_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_activities_ticketId_fkey FOREIGN KEY (ticketId) REFERENCES public.tickets(id)
);
CREATE TABLE public.ticket_ai_insights (
  id text NOT NULL,
  ticketId text NOT NULL,
  suggestedSolutions jsonb NOT NULL,
  sentiment text NOT NULL,
  predictedResolutionTime text NOT NULL,
  similarResolvedTickets integer NOT NULL,
  escalationRisk text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT ticket_ai_insights_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_ai_insights_ticketId_fkey FOREIGN KEY (ticketId) REFERENCES public.tickets(id)
);
CREATE TABLE public.ticket_attachments (
  id text NOT NULL,
  name text NOT NULL,
  size text NOT NULL,
  sizeBytes integer,
  fileType USER-DEFINED NOT NULL DEFAULT 'OTHER'::"FileType",
  url text,
  uploadedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ticketId text NOT NULL,
  uploadedById text,
  tenantId text NOT NULL,
  CONSTRAINT ticket_attachments_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_attachments_ticketId_fkey FOREIGN KEY (ticketId) REFERENCES public.tickets(id)
);
CREATE TABLE public.ticket_categories (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  parentId text,
  color text,
  icon text,
  slaPolicyId text,
  isActive boolean NOT NULL DEFAULT true,
  sortOrder integer NOT NULL DEFAULT 0,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT ticket_categories_pkey PRIMARY KEY (id)
);
CREATE TABLE public.ticket_next_steps (
  id text NOT NULL,
  ticketId text NOT NULL,
  title text NOT NULL,
  dueDate text NOT NULL,
  completed boolean NOT NULL DEFAULT false,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT ticket_next_steps_pkey PRIMARY KEY (id),
  CONSTRAINT ticket_next_steps_ticketId_fkey FOREIGN KEY (ticketId) REFERENCES public.tickets(id)
);
CREATE TABLE public.tickets (
  id text NOT NULL,
  ticketNumber text NOT NULL,
  subject text NOT NULL,
  description text,
  status USER-DEFINED NOT NULL DEFAULT 'OPEN'::"TicketStatus",
  priority USER-DEFINED NOT NULL DEFAULT 'MEDIUM'::"TicketPriority",
  tenantId text NOT NULL,
  slaPolicyId text NOT NULL,
  slaResponseDue timestamp without time zone,
  slaResolutionDue timestamp without time zone,
  slaStatus USER-DEFINED NOT NULL DEFAULT 'ON_TRACK'::"SLAStatus",
  slaBreachedAt timestamp without time zone,
  firstResponseAt timestamp without time zone,
  resolvedAt timestamp without time zone,
  contactId text,
  contactName text NOT NULL,
  contactEmail text NOT NULL,
  assigneeId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  closedAt timestamp without time zone,
  CONSTRAINT tickets_pkey PRIMARY KEY (id),
  CONSTRAINT tickets_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id),
  CONSTRAINT tickets_slaPolicyId_fkey FOREIGN KEY (slaPolicyId) REFERENCES public.sla_policies(id)
);
CREATE TABLE public.tool_call_records (
  id text NOT NULL,
  toolName text NOT NULL,
  toolType text,
  toolVersion text,
  toolInput jsonb,
  toolOutput jsonb,
  inputParameters jsonb,
  outputResult jsonb,
  status text NOT NULL DEFAULT 'PENDING'::text,
  duration integer,
  durationMs integer,
  startedAt timestamp without time zone,
  completedAt timestamp without time zone,
  requiresApproval boolean NOT NULL DEFAULT false,
  isReversible boolean NOT NULL DEFAULT false,
  approvalStatus text,
  approvedBy text,
  approvedAt timestamp without time zone,
  rejectionReason text,
  errorMessage text,
  errorCode text,
  affectedEntityType text,
  affectedEntityId text,
  affectedEntity text,
  changeDescription text,
  rollbackData jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  conversationId text NOT NULL,
  messageId text,
  tenantId text NOT NULL,
  CONSTRAINT tool_call_records_pkey PRIMARY KEY (id),
  CONSTRAINT tool_call_records_conversationId_fkey FOREIGN KEY (conversationId) REFERENCES public.conversation_records(id),
  CONSTRAINT tool_call_records_messageId_fkey FOREIGN KEY (messageId) REFERENCES public.message_records(id)
);
CREATE TABLE public.traffic_sources (
  id text NOT NULL,
  name text NOT NULL,
  percentage integer NOT NULL,
  color text NOT NULL DEFAULT 'bg-ds-primary'::text,
  snapshotDate timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT traffic_sources_pkey PRIMARY KEY (id)
);
CREATE TABLE public.user_permissions (
  id text NOT NULL,
  userId text NOT NULL,
  permissionId text NOT NULL,
  tenantId text NOT NULL,
  granted boolean NOT NULL DEFAULT true,
  reason text,
  grantedBy text,
  grantedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiresAt timestamp without time zone,
  CONSTRAINT user_permissions_pkey PRIMARY KEY (id),
  CONSTRAINT user_permissions_permissionId_fkey FOREIGN KEY (permissionId) REFERENCES public.permissions(id)
);
CREATE TABLE public.user_role_assignments (
  id text NOT NULL,
  userId text NOT NULL,
  roleId text NOT NULL,
  tenantId text NOT NULL,
  assignedBy text,
  assignedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  expiresAt timestamp without time zone,
  CONSTRAINT user_role_assignments_pkey PRIMARY KEY (id),
  CONSTRAINT user_role_assignments_roleId_fkey FOREIGN KEY (roleId) REFERENCES public.rbac_roles(id)
);
CREATE TABLE public.users (
  id text NOT NULL,
  email text NOT NULL,
  name text,
  avatarUrl text,
  role USER-DEFINED NOT NULL DEFAULT 'USER'::"UserRole",
  stripeCustomerId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  preferences jsonb,
  tenantId text NOT NULL,
  timezone text DEFAULT 'UTC'::text,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_tenantId_fkey FOREIGN KEY (tenantId) REFERENCES public.tenants(id)
);
CREATE TABLE public.webhook_deliveries (
  id text NOT NULL,
  endpointId text NOT NULL,
  eventType text NOT NULL,
  payload jsonb NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'PENDING'::"WebhookDeliveryStatus",
  attempts integer NOT NULL DEFAULT 0,
  lastAttemptAt timestamp without time zone,
  responseCode integer,
  responseBody text,
  error text,
  deliveredAt timestamp without time zone,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  tenantId text NOT NULL,
  CONSTRAINT webhook_deliveries_pkey PRIMARY KEY (id),
  CONSTRAINT webhook_deliveries_endpointId_fkey FOREIGN KEY (endpointId) REFERENCES public.webhook_endpoints(id)
);
CREATE TABLE public.webhook_endpoints (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  url text NOT NULL,
  secret text,
  events jsonb NOT NULL,
  headers jsonb,
  isActive boolean NOT NULL DEFAULT true,
  retryCount integer NOT NULL DEFAULT 3,
  timeoutMs integer NOT NULL DEFAULT 30000,
  createdBy text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT webhook_endpoints_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workflow_definitions (
  id text NOT NULL,
  name text NOT NULL,
  description text,
  category text NOT NULL,
  triggerType text NOT NULL,
  triggerConfig jsonb NOT NULL,
  steps jsonb NOT NULL,
  isActive boolean NOT NULL DEFAULT true,
  version integer NOT NULL DEFAULT 1,
  createdBy text NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  tenantId text NOT NULL,
  CONSTRAINT workflow_definitions_pkey PRIMARY KEY (id)
);
CREATE TABLE public.workflow_executions (
  id text NOT NULL,
  workflowId text NOT NULL,
  status USER-DEFINED NOT NULL DEFAULT 'RUNNING'::"WorkflowStatus",
  triggeredBy text NOT NULL,
  triggerData jsonb,
  entityType text,
  entityId text,
  currentStep integer NOT NULL DEFAULT 0,
  stepResults jsonb,
  error text,
  startedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  completedAt timestamp without time zone,
  tenantId text NOT NULL,
  CONSTRAINT workflow_executions_pkey PRIMARY KEY (id),
  CONSTRAINT workflow_executions_workflowId_fkey FOREIGN KEY (workflowId) REFERENCES public.workflow_definitions(id)
);
CREATE TABLE public.workspace_members (
  id text NOT NULL,
  userId text NOT NULL,
  workspaceId text NOT NULL,
  role text NOT NULL DEFAULT 'member'::text,
  isDefault boolean NOT NULL DEFAULT false,
  joinedAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastAccessAt timestamp without time zone,
  CONSTRAINT workspace_members_pkey PRIMARY KEY (id),
  CONSTRAINT workspace_members_workspaceId_fkey FOREIGN KEY (workspaceId) REFERENCES public.workspaces(id)
);
CREATE TABLE public.workspaces (
  id text NOT NULL,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  logoUrl text,
  industry text,
  size text,
  plan text NOT NULL DEFAULT 'free'::text,
  isActive boolean NOT NULL DEFAULT true,
  settings jsonb,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt timestamp without time zone NOT NULL,
  CONSTRAINT workspaces_pkey PRIMARY KEY (id)
);
CREATE TABLE public.zep_episode_audit (
  id text NOT NULL,
  tenantId text NOT NULL DEFAULT 'global'::text,
  previousCount integer NOT NULL,
  newCount integer NOT NULL,
  delta integer NOT NULL,
  operation text NOT NULL,
  sessionId text,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT zep_episode_audit_pkey PRIMARY KEY (id)
);
CREATE TABLE public.zep_episode_usage (
  id text NOT NULL,
  tenantId text NOT NULL DEFAULT 'global'::text,
  episodesUsed integer NOT NULL DEFAULT 0,
  maxEpisodes integer NOT NULL DEFAULT 1000,
  warningPercent integer NOT NULL DEFAULT 80,
  hardLimitPercent integer NOT NULL DEFAULT 95,
  lastUpdated timestamp without time zone NOT NULL,
  createdAt timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
  lastSyncedAt timestamp without time zone,
  lastSyncSuccess boolean NOT NULL DEFAULT false,
  CONSTRAINT zep_episode_usage_pkey PRIMARY KEY (id)
);