import { DomainEvent } from '../shared/DomainEvent';
import { ResponseContent } from './ResponseContent';

/**
 * Event: Auto-response draft was generated by AI
 */
export class AutoResponseGeneratedEvent extends DomainEvent {
  readonly eventType = 'AutoResponseGenerated';

  constructor(
    public readonly draftId: string,
    public readonly leadId: string,
    public readonly tenantId: string,
    public readonly triggerType: string,
    public readonly confidence: number
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      leadId: this.leadId,
      tenantId: this.tenantId,
      triggerType: this.triggerType,
      confidence: this.confidence,
    };
  }
}

/**
 * Event: Auto-response draft was submitted for approval
 */
export class AutoResponseSubmittedForApprovalEvent extends DomainEvent {
  readonly eventType = 'AutoResponseSubmittedForApproval';

  constructor(
    public readonly draftId: string,
    public readonly tenantId: string,
    public readonly approverId: string
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      tenantId: this.tenantId,
      approverId: this.approverId,
    };
  }
}

/**
 * Event: Auto-response draft was approved by human
 */
export class AutoResponseApprovedEvent extends DomainEvent {
  readonly eventType = 'AutoResponseApproved';

  constructor(
    public readonly draftId: string,
    public readonly approvedBy: string,
    public readonly tenantId: string,
    public readonly wasModified: boolean,
    public readonly reason?: string
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      approvedBy: this.approvedBy,
      tenantId: this.tenantId,
      wasModified: this.wasModified,
      reason: this.reason,
    };
  }
}

/**
 * Event: Auto-response draft was rejected by human
 */
export class AutoResponseRejectedEvent extends DomainEvent {
  readonly eventType = 'AutoResponseRejected';

  constructor(
    public readonly draftId: string,
    public readonly rejectedBy: string,
    public readonly tenantId: string,
    public readonly reason: string
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      rejectedBy: this.rejectedBy,
      tenantId: this.tenantId,
      reason: this.reason,
    };
  }
}

/**
 * Event: Auto-response was sent successfully
 */
export class AutoResponseSentEvent extends DomainEvent {
  readonly eventType = 'AutoResponseSent';

  constructor(
    public readonly draftId: string,
    public readonly tenantId: string,
    public readonly notificationId: string,
    public readonly recipientEmail: string
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      tenantId: this.tenantId,
      notificationId: this.notificationId,
      recipientEmail: this.recipientEmail,
    };
  }
}

/**
 * Event: Auto-response draft expired (24h timeout)
 */
export class AutoResponseExpiredEvent extends DomainEvent {
  readonly eventType = 'AutoResponseExpired';

  constructor(
    public readonly draftId: string,
    public readonly tenantId: string
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      tenantId: this.tenantId,
    };
  }
}

/**
 * Event: Auto-response draft was escalated to manager
 */
export class AutoResponseEscalatedEvent extends DomainEvent {
  readonly eventType = 'AutoResponseEscalated';

  constructor(
    public readonly draftId: string,
    public readonly tenantId: string,
    public readonly escalatedTo: string,
    public readonly escalatedBy: string,
    public readonly reason: string
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      tenantId: this.tenantId,
      escalatedTo: this.escalatedTo,
      escalatedBy: this.escalatedBy,
      reason: this.reason,
    };
  }
}

/**
 * Event: Auto-response draft was invalidated (e.g., lead status changed)
 */
export class AutoResponseInvalidatedEvent extends DomainEvent {
  readonly eventType = 'AutoResponseInvalidated';

  constructor(
    public readonly draftId: string,
    public readonly tenantId: string,
    public readonly reason: string
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      tenantId: this.tenantId,
      reason: this.reason,
    };
  }
}

/**
 * Event: Auto-response send failed
 */
export class AutoResponseSendFailedEvent extends DomainEvent {
  readonly eventType = 'AutoResponseSendFailed';

  constructor(
    public readonly draftId: string,
    public readonly tenantId: string,
    public readonly error: string
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      tenantId: this.tenantId,
      error: this.error,
    };
  }
}

/**
 * Event: Auto-response escalation was resolved by manager
 * Added in IFC-029: Transition from ESCALATED -> PENDING_APPROVAL
 */
export class AutoResponseEscalationResolvedEvent extends DomainEvent {
  readonly eventType = 'AutoResponseEscalationResolved';

  constructor(
    public readonly draftId: string,
    public readonly tenantId: string,
    public readonly resolvedBy: string,
    public readonly resolutionFeedback?: string
  ) {
    super();
  }

  toPayload(): Record<string, unknown> {
    return {
      draftId: this.draftId,
      tenantId: this.tenantId,
      resolvedBy: this.resolvedBy,
      resolutionFeedback: this.resolutionFeedback,
    };
  }
}
