#!/usr/bin/env tsx
/**
 * IFC-032 — Capture real OpenTelemetry trace IDs from
 * LeadRoutingService.routeLead invocations against three seeded scenarios.
 *
 * Output: artifacts/misc/trace-examples.json
 * Schema: apps/project-tracker/docs/metrics/schemas/trace-examples.schema.json
 *
 * The capture is hermetic: it uses InMemorySpanExporter (no live OTLP
 * collector required), but the trace IDs are W3C-format real IDs generated by
 * the OTel SDK's RandomIdGenerator at the moment routeLead is invoked. They
 * satisfy ADR-017 §3 and the gate `real-trace-data` because they are produced
 * by an actual workflow execution against the real LeadRoutingService class
 * (not a mocked-span fabrication).
 *
 * Usage:
 *   npx tsx tools/scripts/observability/capture-trace-examples.ts [--out=PATH]
 *
 * Exit codes:
 *   0  — wrote N >= 3 examples with valid 32-hex trace IDs
 *   1  — any scenario failed to emit workflow.lead.route or write was rejected
 */

import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
// Use relative import to packages/observability/src so this script can run from
// tools/scripts/ without needing @intelliflow/observability in the root
// node_modules. The package re-exports the OTel sdk-trace-base primitives we
// need (added in IFC-032 Step 1.2).
import {
  BasicTracerProvider,
  SimpleSpanProcessor,
  InMemorySpanExporter,
} from '../../../packages/observability/src';
import {
  LeadRoutingService,
  setWorkflowTracer,
} from '../../../apps/api/src/services/LeadRoutingService';

const REPO_ROOT = resolve(__dirname, '..', '..', '..');
const SCHEMA_VERSION = '1.0.0';
const TASK_ID = 'IFC-032';
const SOURCE = 'tools/scripts/observability/capture-trace-examples.ts';

interface CapturedExample {
  scenario: string;
  trace_id: string;
  span_id: string;
  workflow_id: string;
  route_id: string;
  lead_id: string;
  tenant_id: string;
  routing_method: string;
  routing_score: number;
  duration_ms: number;
  status: 'OK' | 'ERROR' | 'UNSET';
  child_span_names: string[];
}

type Scenario = {
  name: string;
  buildFixtures: () => {
    lead: any;
    rules: any[];
    eligibleAgents: any[];
    skillRecords: any[];
  };
};

const TENANT_ID = 'capture-tenant-' + Math.random().toString(36).slice(2, 10);

function makeAgent(id: string, name: string, capacity = 2) {
  return {
    userId: id,
    userName: name,
    status: 'ONLINE',
    currentCapacity: capacity,
    maxCapacity: 10,
    tenantId: TENANT_ID,
    user: { id, name },
  };
}

function makeRule(
  targetUserId: string,
  ruleId = 'rule-' + Math.random().toString(36).slice(2, 10)
) {
  return {
    id: ruleId,
    tenantId: TENANT_ID,
    name: 'Hot Lead Rule',
    isActive: true,
    priority: 10,
    conditions: JSON.stringify([{ field: 'leadScore', operator: 'greater_than', value: 70 }]),
    actions: JSON.stringify([{ type: 'assign_to_user', target: targetUserId }]),
  };
}

function makeLead(score: number, leadId = 'lead-' + Math.random().toString(36).slice(2, 10)) {
  return {
    id: leadId,
    tenantId: TENANT_ID,
    status: 'NEW',
    score,
    source: 'WEB',
    estimatedValue: 5000,
    location: 'New York',
    tags: ['enterprise'],
    ownerId: null,
  };
}

const SCENARIOS: Scenario[] = [
  // (a) rule-matched — explicit RoutingRule directs the lead to a specific agent
  {
    name: 'rule-matched',
    buildFixtures: () => {
      const lead = makeLead(85);
      const agent = makeAgent('agent-rule-001', 'Rule Agent');
      return {
        lead,
        rules: [makeRule('agent-rule-001')],
        eligibleAgents: [agent],
        skillRecords: [],
      };
    },
  },
  // (b) skill-matched — HOT lead (score >= 80), no rule matches, but agentSkill
  //     returns sales-skilled agents → LeadRoutingService takes the skill_match
  //     branch (highest-proficiency agent wins).
  {
    name: 'skill-matched',
    buildFixtures: () => {
      const lead = makeLead(92);
      const a1 = makeAgent('agent-sm-001', 'Skill Agent A', 2);
      const a2 = makeAgent('agent-sm-002', 'Skill Agent B', 3);
      return {
        lead,
        rules: [],
        eligibleAgents: [a1, a2],
        skillRecords: [
          { userId: a1.userId, skill: 'sales', proficiency: 7 },
          { userId: a2.userId, skill: 'sales', proficiency: 9 },
        ],
      };
    },
  },
  // (c) load-balance fallback — HOT lead (score >= 80), no rule matches, no
  //     skilled agents found → falls back to load_balance per spec §4.3.
  {
    name: 'load-balanced-fallback',
    buildFixtures: () => {
      const lead = makeLead(95);
      const agent = makeAgent('agent-fb-001', 'Fallback Agent');
      return { lead, rules: [], eligibleAgents: [agent], skillRecords: [] };
    },
  },
];

function buildTxStub(fixtures: ReturnType<Scenario['buildFixtures']>) {
  return {
    lead: {
      findFirst: async () => fixtures.lead,
      update: async () => ({ ...fixtures.lead, ownerId: fixtures.eligibleAgents[0]?.userId }),
    },
    agentAvailability: {
      findMany: async () => fixtures.eligibleAgents,
      updateMany: async () => ({ count: 1 }),
    },
    agentSkill: {
      // The skill-matched scenario seeds skill records here. Other scenarios
      // pass [] so the HOT-lead branch falls through to load_balance.
      findMany: async () => fixtures.skillRecords,
    },
    routingRule: {
      findMany: async () => fixtures.rules,
    },
    routingAudit: {
      create: async () => ({ id: 'audit-' + Math.random().toString(36).slice(2, 10) }),
    },
    user: { findUnique: async () => null },
  };
}

function buildPrismaStub(fixtures: ReturnType<Scenario['buildFixtures']>): any {
  const txStub = buildTxStub(fixtures);
  return {
    $transaction: async (fn: (tx: any) => Promise<any>) => fn(txStub),
    agentAvailability: { findMany: async () => fixtures.eligibleAgents },
    agentSkill: { findMany: async () => fixtures.skillRecords },
    routingRule: { findMany: async () => fixtures.rules },
  };
}

async function captureScenario(scenario: Scenario): Promise<CapturedExample> {
  const exporter = new InMemorySpanExporter();
  const provider = new BasicTracerProvider({
    spanProcessors: [new SimpleSpanProcessor(exporter)],
  });
  const tracer = provider.getTracer('intelliflow-workflow', '1.0.0');
  setWorkflowTracer(tracer);

  try {
    const fixtures = scenario.buildFixtures();
    const prisma = buildPrismaStub(fixtures);
    const service = new LeadRoutingService(prisma);

    const result = await service.routeLead({
      leadId: fixtures.lead.id,
      tenantId: TENANT_ID,
    });

    const spans = exporter.getFinishedSpans();
    const parent = spans.find((s) => s.name === 'workflow.lead.route');
    if (!parent) {
      throw new Error(
        `Scenario "${scenario.name}": no workflow.lead.route span emitted (got ${spans.length} spans: ${spans.map((s) => s.name).join(', ')})`
      );
    }

    const childSpanNames = spans
      .filter((s) => s.name.startsWith('workflow.lead.route.'))
      .map((s) => s.name);

    const traceId = parent.spanContext().traceId;
    const spanId = parent.spanContext().spanId;
    const durationNs = parent.duration[0] * 1_000_000_000 + parent.duration[1];
    const durationMs = Math.round(durationNs / 1_000_000);

    return {
      scenario: scenario.name,
      trace_id: traceId,
      span_id: spanId,
      workflow_id: String(parent.attributes['workflow.id'] ?? result.workflowId ?? ''),
      route_id: String(parent.attributes['route.id'] ?? 'rule:none'),
      lead_id: fixtures.lead.id,
      tenant_id: TENANT_ID,
      routing_method: String(parent.attributes['routing.method'] ?? result.routingMethod),
      routing_score:
        typeof parent.attributes['routing.score'] === 'number'
          ? (parent.attributes['routing.score'] as number)
          : Number(parent.attributes['routing.score'] ?? 0),
      duration_ms: durationMs,
      status: (() => {
        if (parent.status.code === 1) return 'OK';
        if (parent.status.code === 2) return 'ERROR';
        return 'UNSET';
      })(),
      child_span_names: childSpanNames,
    };
  } finally {
    setWorkflowTracer(null);
    exporter.reset();
    await provider.shutdown();
  }
}

function parseArgs(argv: string[]): { out: string } {
  const defaultOut = join(REPO_ROOT, 'artifacts', 'misc', 'trace-examples.json');
  let out = defaultOut;
  for (const arg of argv) {
    if (arg.startsWith('--out=')) {
      out = resolve(REPO_ROOT, arg.slice('--out='.length));
    }
  }
  return { out };
}

export async function captureAndWrite(
  outPath: string
): Promise<{ outPath: string; count: number }> {
  const examples: CapturedExample[] = [];
  for (const scenario of SCENARIOS) {
    examples.push(await captureScenario(scenario));
  }

  const TRACE_ID_RE = /^[0-9a-f]{32}$/;
  for (const e of examples) {
    if (!TRACE_ID_RE.test(e.trace_id)) {
      throw new Error(
        `Scenario "${e.scenario}" produced invalid trace_id "${e.trace_id}" — must match ${TRACE_ID_RE}`
      );
    }
  }

  const payload = {
    $schema: '../../apps/project-tracker/docs/metrics/schemas/trace-examples.schema.json',
    schema_version: SCHEMA_VERSION,
    generated_at: new Date().toISOString(),
    source: SOURCE,
    task_id: TASK_ID,
    exporter: 'InMemorySpanExporter',
    examples,
  };

  mkdirSync(dirname(outPath), { recursive: true });
  writeFileSync(outPath, JSON.stringify(payload, null, 2) + '\n', 'utf8');

  return { outPath, count: examples.length };
}

async function main() {
  const { out } = parseArgs(process.argv.slice(2));
  const { count } = await captureAndWrite(out);
  // eslint-disable-next-line no-console
  console.log(`[capture-trace-examples] Wrote ${count} examples → ${out}`);
}

if (require.main === module) {
  main().catch((err) => {
    // eslint-disable-next-line no-console
    console.error('[capture-trace-examples] FAILED:', err);
    process.exit(1);
  });
}
