import { describe, it, expect, beforeEach, vi } from 'vitest';
import {
  AutoResponseDraft,
  AUTO_RESPONSE_STATUSES,
  TRIGGER_TYPES,
  ALLOWED_LEAD_STATUSES,
  InvalidLeadStatusError,
  TenantMismatchError,
  InvalidStatusTransitionError,
  DraftExpiredError,
  ApprovalRequiredError,
} from '../AutoResponseDraft';
import { AutoResponseDraftId } from '../AutoResponseDraftId';
import { ResponseContent } from '../ResponseContent';
import {
  AutoResponseGeneratedEvent,
  AutoResponseSubmittedForApprovalEvent,
  AutoResponseApprovedEvent,
  AutoResponseRejectedEvent,
  AutoResponseSentEvent,
  AutoResponseExpiredEvent,
  AutoResponseEscalatedEvent,
  AutoResponseInvalidatedEvent,
  AutoResponseSendFailedEvent,
} from '../AutoResponseEvents';

describe('AutoResponseDraft', () => {
  const validContent = ResponseContent.create({
    subject: 'Test Subject',
    body: 'Test body content for the auto-response email.',
  });

  const validCreateProps = {
    tenantId: 'tenant-123',
    leadId: 'lead-456',
    leadTenantId: 'tenant-123',
    leadStatus: 'NEW',
    triggerType: 'EMAIL_RECEIVED' as const,
    content: validContent,
    aiConfidence: 0.85,
    recipientEmail: 'customer@example.com',
  };

  describe('create', () => {
    describe('with valid inputs', () => {
      it('should create a draft with DRAFT status', () => {
        const result = AutoResponseDraft.create(validCreateProps);

        expect(result.isSuccess).toBe(true);
        const draft = result.value;
        expect(draft.status).toBe('DRAFT');
      });

      it('should create a draft with generated ID', () => {
        const result = AutoResponseDraft.create(validCreateProps);

        expect(result.isSuccess).toBe(true);
        const draft = result.value;
        expect(draft.id).toBeInstanceOf(AutoResponseDraftId);
        expect(draft.id.toString()).toMatch(
          /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i
        );
      });

      it('should set expiry to 24 hours by default', () => {
        const result = AutoResponseDraft.create(validCreateProps);

        expect(result.isSuccess).toBe(true);
        const draft = result.value;
        const expectedExpiry = draft.createdAt.getTime() + 24 * 60 * 60 * 1000;
        expect(draft.expiresAt.getTime()).toBe(expectedExpiry);
      });

      it('should set custom expiry hours', () => {
        const result = AutoResponseDraft.create({
          ...validCreateProps,
          expiryHours: 48,
        });

        expect(result.isSuccess).toBe(true);
        const draft = result.value;
        const expectedExpiry = draft.createdAt.getTime() + 48 * 60 * 60 * 1000;
        expect(draft.expiresAt.getTime()).toBe(expectedExpiry);
      });

      it('should emit AutoResponseGeneratedEvent', () => {
        const result = AutoResponseDraft.create(validCreateProps);

        expect(result.isSuccess).toBe(true);
        const draft = result.value;
        const events = draft.domainEvents;
        expect(events).toHaveLength(1);
        expect(events[0]).toBeInstanceOf(AutoResponseGeneratedEvent);
        const event = events[0] as AutoResponseGeneratedEvent;
        expect(event.draftId).toBe(draft.id.toString());
        expect(event.leadId).toBe(validCreateProps.leadId);
        expect(event.tenantId).toBe(validCreateProps.tenantId);
        expect(event.triggerType).toBe(validCreateProps.triggerType);
        expect(event.confidence).toBe(validCreateProps.aiConfidence);
      });

      it('should initialize status history with DRAFT entry', () => {
        const result = AutoResponseDraft.create(validCreateProps);

        expect(result.isSuccess).toBe(true);
        const draft = result.value;
        expect(draft.statusHistory).toHaveLength(1);
        expect(draft.statusHistory[0].status).toBe('DRAFT');
        expect(draft.statusHistory[0].reason).toBe('Generated by AI');
      });

      it.each(ALLOWED_LEAD_STATUSES)(
        'should allow creation for lead status: %s',
        (leadStatus) => {
          const result = AutoResponseDraft.create({
            ...validCreateProps,
            leadStatus,
          });

          expect(result.isSuccess).toBe(true);
        }
      );

      it.each(TRIGGER_TYPES)(
        'should allow creation for trigger type: %s',
        (triggerType) => {
          const result = AutoResponseDraft.create({
            ...validCreateProps,
            triggerType,
          });

          expect(result.isSuccess).toBe(true);
          expect(result.value.triggerType).toBe(triggerType);
        }
      );
    });

    describe('Invariant 1: Lead status validation', () => {
      it('should reject CONVERTED lead status', () => {
        const result = AutoResponseDraft.create({
          ...validCreateProps,
          leadStatus: 'CONVERTED',
        });

        expect(result.isFailure).toBe(true);
        expect(result.error).toBeInstanceOf(InvalidLeadStatusError);
        expect(result.error.code).toBe('INVALID_LEAD_STATUS');
      });

      it('should reject DISQUALIFIED lead status', () => {
        const result = AutoResponseDraft.create({
          ...validCreateProps,
          leadStatus: 'DISQUALIFIED',
        });

        expect(result.isFailure).toBe(true);
        expect(result.error).toBeInstanceOf(InvalidLeadStatusError);
      });

      it('should reject LOST lead status', () => {
        const result = AutoResponseDraft.create({
          ...validCreateProps,
          leadStatus: 'LOST',
        });

        expect(result.isFailure).toBe(true);
        expect(result.error).toBeInstanceOf(InvalidLeadStatusError);
      });

      it('should reject unknown lead status', () => {
        const result = AutoResponseDraft.create({
          ...validCreateProps,
          leadStatus: 'UNKNOWN_STATUS',
        });

        expect(result.isFailure).toBe(true);
        expect(result.error).toBeInstanceOf(InvalidLeadStatusError);
      });
    });

    describe('Invariant 2: Tenant isolation', () => {
      it('should reject when lead tenant does not match', () => {
        const result = AutoResponseDraft.create({
          ...validCreateProps,
          leadTenantId: 'different-tenant',
        });

        expect(result.isFailure).toBe(true);
        expect(result.error).toBeInstanceOf(TenantMismatchError);
        expect(result.error.code).toBe('TENANT_MISMATCH');
      });
    });
  });

  describe('rehydrate', () => {
    it('should rehydrate from persistence data', () => {
      const id = '123e4567-e89b-12d3-a456-426614174000';
      const now = new Date();
      const expiresAt = new Date(now.getTime() + 24 * 60 * 60 * 1000);

      const draft = AutoResponseDraft.rehydrate({
        id,
        tenantId: 'tenant-123',
        leadId: 'lead-456',
        triggerType: 'EMAIL_RECEIVED',
        content: validContent,
        aiConfidence: 0.85,
        status: 'PENDING_APPROVAL',
        statusHistory: [
          { status: 'DRAFT', changedAt: now },
          { status: 'PENDING_APPROVAL', changedAt: now },
        ],
        createdAt: now,
        expiresAt,
        updatedAt: now,
        recipientEmail: 'customer@example.com',
      });

      expect(draft.id.toString()).toBe(id);
      expect(draft.status).toBe('PENDING_APPROVAL');
      expect(draft.statusHistory).toHaveLength(2);
      // Rehydrate should not emit events
      expect(draft.domainEvents).toHaveLength(0);
    });
  });

  describe('submitForApproval', () => {
    it('should transition from DRAFT to PENDING_APPROVAL', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;
      draft.clearDomainEvents();

      const submitResult = draft.submitForApproval('approver-123');

      expect(submitResult.isSuccess).toBe(true);
      expect(draft.status).toBe('PENDING_APPROVAL');
      expect(draft.isPendingApproval).toBe(true);
    });

    it('should emit AutoResponseSubmittedForApprovalEvent', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;
      draft.clearDomainEvents();

      draft.submitForApproval('approver-123');

      const events = draft.domainEvents;
      expect(events).toHaveLength(1);
      expect(events[0]).toBeInstanceOf(AutoResponseSubmittedForApprovalEvent);
      const event = events[0] as AutoResponseSubmittedForApprovalEvent;
      expect(event.approverId).toBe('approver-123');
    });

    it('should add to status history', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;

      draft.submitForApproval('approver-123');

      expect(draft.statusHistory).toHaveLength(2);
      expect(draft.statusHistory[1].status).toBe('PENDING_APPROVAL');
      expect(draft.statusHistory[1].changedBy).toBe('approver-123');
    });

    it('should fail if not in DRAFT status', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;
      draft.submitForApproval('approver-123');

      const secondSubmit = draft.submitForApproval('approver-456');

      expect(secondSubmit.isFailure).toBe(true);
      expect(secondSubmit.error).toBeInstanceOf(InvalidStatusTransitionError);
    });

    it('should fail if expired', () => {
      const result = AutoResponseDraft.create({
        ...validCreateProps,
        expiryHours: 0, // Immediately expired
      });
      const draft = result.value;

      // Fast forward past expiry
      vi.useFakeTimers();
      vi.advanceTimersByTime(1000);

      const submitResult = draft.submitForApproval('approver-123');

      expect(submitResult.isFailure).toBe(true);
      expect(submitResult.error).toBeInstanceOf(DraftExpiredError);
      expect(draft.status).toBe('INVALIDATED');

      vi.useRealTimers();
    });
  });

  describe('approve', () => {
    let draft: AutoResponseDraft;

    beforeEach(() => {
      const result = AutoResponseDraft.create(validCreateProps);
      draft = result.value;
      draft.submitForApproval('approver-123');
      draft.clearDomainEvents();
    });

    it('should transition from PENDING_APPROVAL to APPROVED', () => {
      const approveResult = draft.approve('approver-123');

      expect(approveResult.isSuccess).toBe(true);
      expect(draft.status).toBe('APPROVED');
      expect(draft.isApproved).toBe(true);
      expect(draft.canBeSent).toBe(true);
    });

    it('should emit AutoResponseApprovedEvent', () => {
      draft.approve('approver-123', undefined, 'Looks good');

      const events = draft.domainEvents;
      expect(events).toHaveLength(1);
      expect(events[0]).toBeInstanceOf(AutoResponseApprovedEvent);
      const event = events[0] as AutoResponseApprovedEvent;
      expect(event.approvedBy).toBe('approver-123');
      expect(event.reason).toBe('Looks good');
      expect(event.wasModified).toBe(false);
    });

    it('should record approval decision', () => {
      draft.approve('approver-123', undefined, 'LGTM');

      expect(draft.approvalDecision).toBeDefined();
      expect(draft.approvalDecision!.decision).toBe('APPROVED');
      expect(draft.approvalDecision!.decidedBy).toBe('approver-123');
      expect(draft.approvalDecision!.reason).toBe('LGTM');
    });

    it('should apply content modifications', () => {
      const modifications = {
        subject: 'Modified Subject',
        body: 'Modified body content',
      };

      draft.approve('approver-123', modifications);

      expect(draft.content.subject).toBe('Modified Subject');
      expect(draft.content.body).toBe('Modified body content');
      expect(draft.approvalDecision!.modifications).toEqual(modifications);
    });

    it('should emit event with wasModified=true when modifications applied', () => {
      draft.approve('approver-123', { subject: 'New Subject' });

      const event = draft.domainEvents[0] as AutoResponseApprovedEvent;
      expect(event.wasModified).toBe(true);
    });

    it('should fail if not in PENDING_APPROVAL status', () => {
      const freshResult = AutoResponseDraft.create(validCreateProps);
      const freshDraft = freshResult.value;

      const approveResult = freshDraft.approve('approver-123');

      expect(approveResult.isFailure).toBe(true);
      expect(approveResult.error).toBeInstanceOf(InvalidStatusTransitionError);
    });

    it('should fail if expired', () => {
      vi.useFakeTimers();
      // Create with very short expiry
      const shortResult = AutoResponseDraft.create({
        ...validCreateProps,
        expiryHours: 0,
      });
      const shortDraft = shortResult.value;
      shortDraft.submitForApproval('approver-123');
      vi.advanceTimersByTime(1000);

      const approveResult = shortDraft.approve('approver-123');

      expect(approveResult.isFailure).toBe(true);
      expect(approveResult.error).toBeInstanceOf(DraftExpiredError);

      vi.useRealTimers();
    });
  });

  describe('reject', () => {
    let draft: AutoResponseDraft;

    beforeEach(() => {
      const result = AutoResponseDraft.create(validCreateProps);
      draft = result.value;
      draft.submitForApproval('approver-123');
      draft.clearDomainEvents();
    });

    it('should transition from PENDING_APPROVAL to REJECTED', () => {
      const rejectResult = draft.reject('approver-123', 'Inappropriate content');

      expect(rejectResult.isSuccess).toBe(true);
      expect(draft.status).toBe('REJECTED');
    });

    it('should emit AutoResponseRejectedEvent', () => {
      draft.reject('approver-123', 'Inappropriate content');

      const events = draft.domainEvents;
      expect(events).toHaveLength(1);
      expect(events[0]).toBeInstanceOf(AutoResponseRejectedEvent);
      const event = events[0] as AutoResponseRejectedEvent;
      expect(event.rejectedBy).toBe('approver-123');
      expect(event.reason).toBe('Inappropriate content');
    });

    it('should record rejection decision', () => {
      draft.reject('approver-123', 'Needs manual response');

      expect(draft.approvalDecision).toBeDefined();
      expect(draft.approvalDecision!.decision).toBe('REJECTED');
      expect(draft.approvalDecision!.decidedBy).toBe('approver-123');
      expect(draft.approvalDecision!.reason).toBe('Needs manual response');
    });

    it('should fail if not in PENDING_APPROVAL status', () => {
      draft.approve('approver-123');

      const rejectResult = draft.reject('approver-456', 'Too late');

      expect(rejectResult.isFailure).toBe(true);
      expect(rejectResult.error).toBeInstanceOf(InvalidStatusTransitionError);
    });
  });

  describe('markSent', () => {
    let draft: AutoResponseDraft;

    beforeEach(() => {
      const result = AutoResponseDraft.create(validCreateProps);
      draft = result.value;
      draft.submitForApproval('approver-123');
      draft.approve('approver-123');
      draft.clearDomainEvents();
    });

    it('should transition from APPROVED to SENT', () => {
      const sentResult = draft.markSent('notification-789');

      expect(sentResult.isSuccess).toBe(true);
      expect(draft.status).toBe('SENT');
    });

    it('should emit AutoResponseSentEvent', () => {
      draft.markSent('notification-789');

      const events = draft.domainEvents;
      expect(events).toHaveLength(1);
      expect(events[0]).toBeInstanceOf(AutoResponseSentEvent);
      const event = events[0] as AutoResponseSentEvent;
      expect(event.notificationId).toBe('notification-789');
      expect(event.recipientEmail).toBe('customer@example.com');
    });

    it('should fail with ApprovalRequiredError if in DRAFT status', () => {
      const freshResult = AutoResponseDraft.create(validCreateProps);
      const freshDraft = freshResult.value;

      const sentResult = freshDraft.markSent('notification-789');

      expect(sentResult.isFailure).toBe(true);
      expect(sentResult.error).toBeInstanceOf(ApprovalRequiredError);
      expect(sentResult.error.code).toBe('APPROVAL_REQUIRED');
    });

    it('should fail with ApprovalRequiredError if in PENDING_APPROVAL status', () => {
      const pendingResult = AutoResponseDraft.create(validCreateProps);
      const pendingDraft = pendingResult.value;
      pendingDraft.submitForApproval('approver-123');

      const sentResult = pendingDraft.markSent('notification-789');

      expect(sentResult.isFailure).toBe(true);
      expect(sentResult.error).toBeInstanceOf(ApprovalRequiredError);
    });

    it('should fail if in REJECTED status', () => {
      const rejectedResult = AutoResponseDraft.create(validCreateProps);
      const rejectedDraft = rejectedResult.value;
      rejectedDraft.submitForApproval('approver-123');
      rejectedDraft.reject('approver-123', 'No');

      const sentResult = rejectedDraft.markSent('notification-789');

      expect(sentResult.isFailure).toBe(true);
      expect(sentResult.error).toBeInstanceOf(InvalidStatusTransitionError);
    });
  });

  describe('markSendFailed', () => {
    let draft: AutoResponseDraft;

    beforeEach(() => {
      const result = AutoResponseDraft.create(validCreateProps);
      draft = result.value;
      draft.submitForApproval('approver-123');
      draft.approve('approver-123');
      draft.clearDomainEvents();
    });

    it('should transition from APPROVED to FAILED', () => {
      const failResult = draft.markSendFailed('SMTP connection failed');

      expect(failResult.isSuccess).toBe(true);
      expect(draft.status).toBe('FAILED');
    });

    it('should emit AutoResponseSendFailedEvent', () => {
      draft.markSendFailed('Email service unavailable');

      const events = draft.domainEvents;
      expect(events).toHaveLength(1);
      expect(events[0]).toBeInstanceOf(AutoResponseSendFailedEvent);
      const event = events[0] as AutoResponseSendFailedEvent;
      expect(event.error).toBe('Email service unavailable');
    });

    it('should fail if not in APPROVED status', () => {
      const freshResult = AutoResponseDraft.create(validCreateProps);
      const freshDraft = freshResult.value;

      const failResult = freshDraft.markSendFailed('Error');

      expect(failResult.isFailure).toBe(true);
      expect(failResult.error).toBeInstanceOf(InvalidStatusTransitionError);
    });
  });

  describe('escalate', () => {
    let draft: AutoResponseDraft;

    beforeEach(() => {
      const result = AutoResponseDraft.create(validCreateProps);
      draft = result.value;
      draft.submitForApproval('approver-123');
      draft.clearDomainEvents();
    });

    it('should transition from PENDING_APPROVAL to ESCALATED', () => {
      const escalateResult = draft.escalate(
        'approver-123',
        'manager-456',
        'Needs senior review'
      );

      expect(escalateResult.isSuccess).toBe(true);
      expect(draft.status).toBe('ESCALATED');
    });

    it('should emit AutoResponseEscalatedEvent', () => {
      draft.escalate('approver-123', 'manager-456', 'Complex case');

      const events = draft.domainEvents;
      expect(events).toHaveLength(1);
      expect(events[0]).toBeInstanceOf(AutoResponseEscalatedEvent);
      const event = events[0] as AutoResponseEscalatedEvent;
      expect(event.escalatedTo).toBe('manager-456');
      expect(event.escalatedBy).toBe('approver-123');
      expect(event.reason).toBe('Complex case');
    });

    it('should record escalation details', () => {
      draft.escalate('approver-123', 'manager-456', 'Sensitive topic', 72);

      expect(draft.escalation).toBeDefined();
      expect(draft.escalation!.escalatedTo).toBe('manager-456');
      expect(draft.escalation!.escalatedBy).toBe('approver-123');
      expect(draft.escalation!.reason).toBe('Sensitive topic');
      // Check escalation expiry is 72 hours from escalation time
      const escalatedAt = draft.escalation!.escalatedAt;
      const expectedExpiry = escalatedAt.getTime() + 72 * 60 * 60 * 1000;
      expect(draft.escalation!.expiresAt.getTime()).toBe(expectedExpiry);
    });

    it('should default escalation expiry to 48 hours', () => {
      draft.escalate('approver-123', 'manager-456', 'Needs review');

      const escalatedAt = draft.escalation!.escalatedAt;
      const expectedExpiry = escalatedAt.getTime() + 48 * 60 * 60 * 1000;
      expect(draft.escalation!.expiresAt.getTime()).toBe(expectedExpiry);
    });

    it('should fail if not in PENDING_APPROVAL status', () => {
      draft.approve('approver-123');

      const escalateResult = draft.escalate(
        'approver-123',
        'manager-456',
        'Too late'
      );

      expect(escalateResult.isFailure).toBe(true);
      expect(escalateResult.error).toBeInstanceOf(InvalidStatusTransitionError);
    });
  });

  describe('invalidate', () => {
    it('should transition to INVALIDATED from DRAFT', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;
      draft.clearDomainEvents();

      draft.invalidate('Lead status changed to CONVERTED');

      expect(draft.status).toBe('INVALIDATED');
    });

    it('should transition to INVALIDATED from PENDING_APPROVAL', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;
      draft.submitForApproval('approver-123');
      draft.clearDomainEvents();

      draft.invalidate('Lead disqualified');

      expect(draft.status).toBe('INVALIDATED');
    });

    it('should emit AutoResponseInvalidatedEvent', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;
      draft.clearDomainEvents();

      draft.invalidate('Lead status changed');

      const events = draft.domainEvents;
      expect(events).toHaveLength(1);
      expect(events[0]).toBeInstanceOf(AutoResponseInvalidatedEvent);
      const event = events[0] as AutoResponseInvalidatedEvent;
      expect(event.reason).toBe('Lead status changed');
    });

    it('should not change status if already SENT', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;
      draft.submitForApproval('approver-123');
      draft.approve('approver-123');
      draft.markSent('notification-123');
      draft.clearDomainEvents();

      draft.invalidate('Too late');

      expect(draft.status).toBe('SENT');
      expect(draft.domainEvents).toHaveLength(0);
    });

    it('should not change status if already REJECTED', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;
      draft.submitForApproval('approver-123');
      draft.reject('approver-123', 'No');
      draft.clearDomainEvents();

      draft.invalidate('Lead changed');

      expect(draft.status).toBe('REJECTED');
      expect(draft.domainEvents).toHaveLength(0);
    });

    it('should not change status if already INVALIDATED', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;
      draft.invalidate('First reason');
      draft.clearDomainEvents();

      draft.invalidate('Second reason');

      expect(draft.statusHistory.filter(h => h.status === 'INVALIDATED')).toHaveLength(1);
      expect(draft.domainEvents).toHaveLength(0);
    });
  });

  describe('checkExpiry', () => {
    it('should return false if not expired', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;

      const wasExpired = draft.checkExpiry();

      expect(wasExpired).toBe(false);
      expect(draft.status).toBe('DRAFT');
    });

    it('should mark as expired and return true if past expiry', () => {
      vi.useFakeTimers();

      const result = AutoResponseDraft.create({
        ...validCreateProps,
        expiryHours: 1,
      });
      const draft = result.value;
      draft.clearDomainEvents();

      // Fast forward past 1 hour
      vi.advanceTimersByTime(2 * 60 * 60 * 1000);

      const wasExpired = draft.checkExpiry();

      expect(wasExpired).toBe(true);
      expect(draft.status).toBe('INVALIDATED');
      expect(draft.domainEvents).toHaveLength(1);
      expect(draft.domainEvents[0]).toBeInstanceOf(AutoResponseExpiredEvent);

      vi.useRealTimers();
    });

    it('should not mark as expired if already SENT', () => {
      vi.useFakeTimers();

      const result = AutoResponseDraft.create({
        ...validCreateProps,
        expiryHours: 1,
      });
      const draft = result.value;
      draft.submitForApproval('approver-123');
      draft.approve('approver-123');
      draft.markSent('notification-123');
      draft.clearDomainEvents();

      vi.advanceTimersByTime(2 * 60 * 60 * 1000);

      const wasExpired = draft.checkExpiry();

      expect(wasExpired).toBe(false);
      expect(draft.status).toBe('SENT');

      vi.useRealTimers();
    });
  });

  describe('getters', () => {
    it('should return all properties correctly', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;

      expect(draft.tenantId).toBe('tenant-123');
      expect(draft.leadId).toBe('lead-456');
      expect(draft.triggerType).toBe('EMAIL_RECEIVED');
      expect(draft.content).toBe(validContent);
      expect(draft.aiConfidence).toBe(0.85);
      expect(draft.recipientEmail).toBe('customer@example.com');
      expect(draft.createdAt).toBeInstanceOf(Date);
      expect(draft.expiresAt).toBeInstanceOf(Date);
      expect(draft.updatedAt).toBeInstanceOf(Date);
    });

    it('should return isExpired correctly', () => {
      vi.useFakeTimers();

      const result = AutoResponseDraft.create({
        ...validCreateProps,
        expiryHours: 1,
      });
      const draft = result.value;

      expect(draft.isExpired).toBe(false);

      vi.advanceTimersByTime(2 * 60 * 60 * 1000);

      expect(draft.isExpired).toBe(true);

      vi.useRealTimers();
    });

    it('should return canBeSent correctly', () => {
      const result = AutoResponseDraft.create(validCreateProps);
      const draft = result.value;

      expect(draft.canBeSent).toBe(false); // DRAFT

      draft.submitForApproval('approver-123');
      expect(draft.canBeSent).toBe(false); // PENDING_APPROVAL

      draft.approve('approver-123');
      expect(draft.canBeSent).toBe(true); // APPROVED

      draft.markSent('notification-123');
      expect(draft.canBeSent).toBe(false); // SENT (terminal)
    });
  });

  describe('status constants', () => {
    it('should export all status values', () => {
      expect(AUTO_RESPONSE_STATUSES).toContain('DRAFT');
      expect(AUTO_RESPONSE_STATUSES).toContain('PENDING_APPROVAL');
      expect(AUTO_RESPONSE_STATUSES).toContain('APPROVED');
      expect(AUTO_RESPONSE_STATUSES).toContain('REJECTED');
      expect(AUTO_RESPONSE_STATUSES).toContain('INVALIDATED');
      expect(AUTO_RESPONSE_STATUSES).toContain('SENT');
      expect(AUTO_RESPONSE_STATUSES).toContain('FAILED');
      expect(AUTO_RESPONSE_STATUSES).toContain('ESCALATED');
    });

    it('should export all trigger types', () => {
      expect(TRIGGER_TYPES).toContain('EMAIL_RECEIVED');
      expect(TRIGGER_TYPES).toContain('FORM_SUBMIT');
      expect(TRIGGER_TYPES).toContain('CHAT_MESSAGE');
      expect(TRIGGER_TYPES).toContain('MANUAL');
    });

    it('should export allowed lead statuses', () => {
      expect(ALLOWED_LEAD_STATUSES).toContain('NEW');
      expect(ALLOWED_LEAD_STATUSES).toContain('CONTACTED');
      expect(ALLOWED_LEAD_STATUSES).toContain('QUALIFIED');
      expect(ALLOWED_LEAD_STATUSES).toContain('NURTURING');
    });
  });
});
