import { describe, it, expect } from 'vitest';
import {
  accountHierarchyConfigSchema,
  accountIndustryOptionSchema,
  createAccountIndustryOptionSchema,
  updateAccountIndustryOptionSchema,
  deleteAccountIndustryOptionSchema,
  accountCustomFieldDataTypeSchema,
  createAccountCustomFieldSchema,
  updateAccountCustomFieldSchema,
  deleteAccountCustomFieldSchema,
  generateIndustryKey,
  DEFAULT_ACCOUNT_INDUSTRIES,
  updateAccountDuplicateRulesSchema,
} from '../account-settings';

describe('account-settings validators', () => {
  describe('generateIndustryKey', () => {
    it('normalizes spaces and punctuation to underscores', () => {
      expect(generateIndustryKey('Software & SaaS')).toBe('software_saas');
    });
    it('strips leading/trailing underscores', () => {
      expect(generateIndustryKey('  Hello World  ')).toBe('hello_world');
    });
    it('lowercases', () => {
      expect(generateIndustryKey('RETAIL')).toBe('retail');
    });
    it('collapses multiple non-alphanum chars', () => {
      expect(generateIndustryKey('A / B / C')).toBe('a_b_c');
    });
  });

  describe('DEFAULT_ACCOUNT_INDUSTRIES', () => {
    it('contains 12 entries', () => {
      expect(DEFAULT_ACCOUNT_INDUSTRIES).toHaveLength(12);
    });
    it('all keys match generateIndustryKey(label)', () => {
      for (const { label, key } of DEFAULT_ACCOUNT_INDUSTRIES) {
        expect(key).toBe(generateIndustryKey(label));
      }
    });
    it('all keys match the key regex', () => {
      for (const { key } of DEFAULT_ACCOUNT_INDUSTRIES) {
        expect(key).toMatch(/^[a-z0-9_]+$/);
      }
    });
  });

  describe('accountHierarchyConfigSchema', () => {
    it('accepts a valid config', () => {
      const result = accountHierarchyConfigSchema.safeParse({
        maxDepth: 5,
        requireParentForTiers: ['enterprise'],
        preventCycles: true,
      });
      expect(result.success).toBe(true);
    });
    it('rejects maxDepth = 0', () => {
      const result = accountHierarchyConfigSchema.safeParse({
        maxDepth: 0,
        requireParentForTiers: [],
        preventCycles: true,
      });
      expect(result.success).toBe(false);
    });
    it('rejects maxDepth = 11', () => {
      const result = accountHierarchyConfigSchema.safeParse({
        maxDepth: 11,
        requireParentForTiers: [],
        preventCycles: true,
      });
      expect(result.success).toBe(false);
    });
    it('accepts maxDepth = 1 and 10 (boundaries)', () => {
      expect(
        accountHierarchyConfigSchema.safeParse({
          maxDepth: 1,
          requireParentForTiers: [],
          preventCycles: true,
        }).success
      ).toBe(true);
      expect(
        accountHierarchyConfigSchema.safeParse({
          maxDepth: 10,
          requireParentForTiers: [],
          preventCycles: false,
        }).success
      ).toBe(true);
    });
    it('rejects non-boolean preventCycles', () => {
      const result = accountHierarchyConfigSchema.safeParse({
        maxDepth: 5,
        requireParentForTiers: [],
        preventCycles: 'yes' as unknown as boolean,
      });
      expect(result.success).toBe(false);
    });
  });

  describe('accountIndustryOptionSchema', () => {
    it('accepts a valid option', () => {
      const result = accountIndustryOptionSchema.safeParse({
        label: 'Retail',
        key: 'retail',
        sortOrder: 0,
        isActive: true,
      });
      expect(result.success).toBe(true);
    });
    it('rejects an uppercase key', () => {
      const result = accountIndustryOptionSchema.safeParse({
        label: 'Retail',
        key: 'Retail',
        sortOrder: 0,
        isActive: true,
      });
      expect(result.success).toBe(false);
    });
    it('rejects key with dash', () => {
      const result = accountIndustryOptionSchema.safeParse({
        label: 'Retail',
        key: 'retail-store',
        sortOrder: 0,
        isActive: true,
      });
      expect(result.success).toBe(false);
    });
    it('rejects negative sortOrder', () => {
      const result = accountIndustryOptionSchema.safeParse({
        label: 'Retail',
        key: 'retail',
        sortOrder: -1,
        isActive: true,
      });
      expect(result.success).toBe(false);
    });
    it('rejects blank label', () => {
      const result = accountIndustryOptionSchema.safeParse({
        label: '',
        key: 'retail',
        sortOrder: 0,
        isActive: true,
      });
      expect(result.success).toBe(false);
    });
  });

  describe('createAccountIndustryOptionSchema', () => {
    it('accepts label only (key auto-generated by router)', () => {
      const result = createAccountIndustryOptionSchema.safeParse({ label: 'Agriculture' });
      expect(result.success).toBe(true);
    });
    it('rejects label > 100 chars', () => {
      const result = createAccountIndustryOptionSchema.safeParse({ label: 'x'.repeat(101) });
      expect(result.success).toBe(false);
    });
  });

  describe('updateAccountIndustryOptionSchema', () => {
    it('requires id', () => {
      const result = updateAccountIndustryOptionSchema.safeParse({ label: 'x' });
      expect(result.success).toBe(false);
    });
    it('allows partial fields beyond id', () => {
      const result = updateAccountIndustryOptionSchema.safeParse({
        id: 'abc',
        isActive: false,
      });
      expect(result.success).toBe(true);
    });
  });

  describe('deleteAccountIndustryOptionSchema', () => {
    it('requires id', () => {
      expect(deleteAccountIndustryOptionSchema.safeParse({}).success).toBe(false);
    });
    it('accepts id', () => {
      expect(deleteAccountIndustryOptionSchema.safeParse({ id: 'abc' }).success).toBe(true);
    });
  });

  describe('accountCustomFieldDataTypeSchema', () => {
    it.each(['text', 'number', 'currency', 'dropdown', 'date', 'boolean'])('accepts %s', (v) => {
      expect(accountCustomFieldDataTypeSchema.safeParse(v).success).toBe(true);
    });
    it('rejects unknown type', () => {
      expect(accountCustomFieldDataTypeSchema.safeParse('blob').success).toBe(false);
    });
  });

  describe('createAccountCustomFieldSchema', () => {
    it('accepts minimal text field', () => {
      const result = createAccountCustomFieldSchema.safeParse({
        fieldName: 'Region',
        dataType: 'text',
      });
      expect(result.success).toBe(true);
    });
    it('accepts dropdown with options', () => {
      const result = createAccountCustomFieldSchema.safeParse({
        fieldName: 'Tier',
        dataType: 'dropdown',
        options: { values: ['Gold', 'Silver'] },
        isRequired: true,
      });
      expect(result.success).toBe(true);
    });
    it('rejects missing fieldName', () => {
      const result = createAccountCustomFieldSchema.safeParse({ dataType: 'text' });
      expect(result.success).toBe(false);
    });
  });

  describe('updateAccountCustomFieldSchema', () => {
    it('requires id in addition to create fields', () => {
      const result = updateAccountCustomFieldSchema.safeParse({
        fieldName: 'Region',
        dataType: 'text',
      });
      expect(result.success).toBe(false);
    });
    it('accepts full payload with id', () => {
      const result = updateAccountCustomFieldSchema.safeParse({
        id: 'abc',
        fieldName: 'Region',
        dataType: 'text',
      });
      expect(result.success).toBe(true);
    });
  });

  describe('deleteAccountCustomFieldSchema', () => {
    it('requires id', () => {
      expect(deleteAccountCustomFieldSchema.safeParse({}).success).toBe(false);
    });
    it('accepts id', () => {
      expect(deleteAccountCustomFieldSchema.safeParse({ id: 'abc' }).success).toBe(true);
    });
  });

  describe('updateAccountDuplicateRulesSchema superRefine', () => {
    const rule = (field: string, strat: string) => ({
      field,
      matchStrategy: strat,
      threshold: 100,
      isActive: true,
      sortOrder: 0,
    });

    it('accepts unique (field, strategy) pairs', () => {
      const result = updateAccountDuplicateRulesSchema.safeParse({
        rules: [rule('name', 'fuzzy'), rule('website', 'normalized')],
      });
      expect(result.success).toBe(true);
    });

    it('rejects duplicate (field, strategy) pairs', () => {
      const result = updateAccountDuplicateRulesSchema.safeParse({
        rules: [rule('name', 'fuzzy'), rule('name', 'fuzzy')],
      });
      expect(result.success).toBe(false);
      if (!result.success) {
        expect(result.error.issues[0].message).toMatch(/duplicate/i);
      }
    });

    it('accepts same field with different strategy', () => {
      const result = updateAccountDuplicateRulesSchema.safeParse({
        rules: [rule('name', 'fuzzy'), rule('name', 'exact')],
      });
      expect(result.success).toBe(true);
    });

    it('requires at least one rule', () => {
      const result = updateAccountDuplicateRulesSchema.safeParse({ rules: [] });
      expect(result.success).toBe(false);
    });
  });
});
