"""
Tests for the --message-file mode of tools/audit/commit_msg_lint.py.

This mode is what the .husky/commit-msg hook calls to validate a single pending
commit message, and it shares _lint_message() with the range/count modes the
pre-ship gate and CI system-audit use. Covering it here guarantees the
local hook and the CI gate can't diverge on the rules (the drift that let an
upper-case subject pass locally and red in CI — #340).
"""
from __future__ import annotations

import os
import subprocess
import sys
import tempfile
from pathlib import Path

SCRIPT = Path(__file__).resolve().parents[1] / "commit_msg_lint.py"


def _lint(message: str) -> tuple[int, str]:
    """Run the linter in --message-file mode on *message*; return (code, output)."""
    with tempfile.NamedTemporaryFile(
        "w", suffix=".txt", delete=False, encoding="utf-8"
    ) as f:
        f.write(message)
        path = f.name
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), "--message-file", path],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return proc.returncode, proc.stdout + proc.stderr


def test_valid_message_passes():
    code, _ = _lint("feat(api): add a perfectly fine subject line\n")
    assert code == 0


def test_upper_case_subject_fails():
    # The exact gap that let #340 through: subject starts with a capital letter.
    code, out = _lint("feat(ai-worker): OpenRouter fallback for resilience\n")
    assert code == 1
    assert "upper-case" in out


def test_subject_too_short_fails():
    code, _ = _lint("fix(api): a\n")
    assert code == 1


def test_subject_trailing_period_fails():
    code, _ = _lint("fix(api): resolve the flaky pool timeout.\n")
    assert code == 1


def test_long_body_line_fails():
    code, _ = _lint("fix(api): valid lowercase subject here\n\n" + "x" * 120 + "\n")
    assert code == 1


def test_ai_coauthor_trailer_fails():
    code, out = _lint(
        "fix(api): valid lowercase subject here\n\n"
        "Co-Authored-By: Claude <noreply@anthropic.com>\n"
    )
    assert code == 1


import pytest

VALID_HEADER = "fix(api): valid lowercase subject here\n\n"


@pytest.mark.parametrize(
    "line",
    [
        "Co-Authored-By: Claude Opus <noreply@anthropic.com>",
        "Co-authored-by: Copilot <175728472+Copilot@users.noreply.github.com>",
        "Co-authored-by: Codex <codex@example.com>",
        "🤖 Generated with [Claude Code](https://claude.com/claude-code)",
        "Generated with Claude Code",
        "Claude-Session: https://claude.ai/code/session_0187a7RpeGUyXk8avzLbCrv7",
        "https://claude.ai/code/session_0187a7RpeGUyXk8avzLbCrv7",
    ],
)
def test_every_ai_attribution_shape_fails(line):
    # #754: the session trailer and bare session link passed the old rule.
    code, out = _lint(VALID_HEADER + "Body text.\n\n" + line + "\n")
    assert code == 1, out
    assert "AI attribution" in out


@pytest.mark.parametrize(
    "line",
    [
        "Co-authored-by: Claude Opus 4.7 <noreply@anthropic.com>",
        "Co-authored-by: GitHub Copilot <x@example.com>",
        "Co-authored-by: Cursor Agent <cursoragent@cursor.com>",
        "Co-authored-by: Gemini Code Assist <bot@example.com>",
        "Generated by Anthropic",
        "Generated with Anthropic's Claude",
    ],
)
def test_review_round_ai_shapes_fail(line):
    # Codex adversarial review on #754: "Generated by Anthropic" slipped through.
    code, out = _lint(VALID_HEADER + "Body text.\n\n" + line + "\n")
    assert code == 1, out


@pytest.mark.parametrize(
    "line",
    [
        "Co-authored-by: Claude Dupont <claude.dupont@example.com>",
        "Co-authored-by: Gemini Rossi <gemini.rossi@example.com>",
        "Co-authored-by: Cursor Smith <c.smith@example.com>",
    ],
)
def test_human_coauthors_sharing_a_tool_word_pass(line):
    # Code review on #754: matching any tool word in the name blocked real people.
    code, out = _lint(VALID_HEADER + "Body text.\n\n" + line + "\n")
    assert code == 0, out


@pytest.mark.parametrize(
    "line",
    [
        "Co-authored-by: Claude Opus 4.7 (1M context) <x@y.com>",
        "Co-Authored-By: Claude Opus 4.7 [1M] <x@y.com>",
        "Co-authored-by: Devin AI <a@b.com>",
        "Generated using Claude Code",
        "Created with the Copilot agent",
    ],
)
def test_review_round_two_ai_shapes_fail(line):
    # Round-2 reviews on #754: label suffixes, other tools, "using".
    code, out = _lint(VALID_HEADER + "Body text.\n\n" + line + "\n")
    assert code == 1, out


@pytest.mark.parametrize(
    "line",
    [
        "Generated by the ORM; cursor pagination keeps pages stable.",
        "Auto-regenerated with prisma, see cursor docs.",
        "Generated with prisma, then Claude reviewed it.",
    ],
)
def test_prose_mentioning_a_tool_word_passes(line):
    # Round-2 code review on #754: the footer rule matched ordinary prose.
    code, out = _lint(VALID_HEADER + line + "\n")
    assert code == 0, out


@pytest.mark.parametrize(
    "line",
    [
        "Generated with OpenAI Codex",
        "Generated with GitHub Copilot",
        "Created with Anthropic's Claude",
        "Co-authored-by: Claude Mythos <x@example.com>",
    ],
)
def test_review_round_three_ai_shapes_fail(line):
    # Round-3 reviews on #754: vendor-prefixed tool names, unlisted model names.
    code, out = _lint(VALID_HEADER + "Body text.\n\n" + line + "\n")
    assert code == 1, out


@pytest.mark.parametrize(
    "line",
    [
        "Pagination created with cursor-based paging.",
        "Refactor written using Aider-style diffs.",
        "Authored by Devin Smith.",
    ],
)
def test_round_four_prose_with_tool_words_passes(line):
    # Round-4 code review on #754: a tool word followed by ordinary prose.
    code, out = _lint(VALID_HEADER + line + "\n")
    assert code == 0, out


def test_vendor_prefix_alone_is_not_attribution():
    code, out = _lint(VALID_HEADER + "Generated with GitHub Actions, then reviewed.\n")
    assert code == 0, out


def test_attribution_in_a_merge_commit_still_fails():
    # Merge/revert subjects skip the format rules, never the attribution rule.
    code, out = _lint("Merge branch 'x'\n\nClaude-Session: https://claude.ai/code/session_1\n")
    assert code == 1, out


def test_human_coauthor_and_plain_mentions_pass():
    code, out = _lint(
        VALID_HEADER
        + "Fix the Claude API client retry (mentions a product, not attribution).\n\n"
        + "Co-authored-by: Jane Doe <jane@example.com>\n"
    )
    assert code == 0, out


def _lint_pr(text: str) -> tuple[int, str]:
    with tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8") as f:
        f.write(text)
        path = f.name
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), "--pr-text-file", path],
        capture_output=True,
        text=True,
        encoding="utf-8",
    )
    return proc.returncode, proc.stdout + proc.stderr


def test_pr_text_with_generated_footer_fails():
    code, out = _lint_pr(
        "fix(ci): something\n\nBody #753.\n\n"
        "🤖 Generated with [Claude Code](https://claude.com/claude-code)\n\n"
        "https://claude.ai/code/session_0187a7RpeGUyXk8avzLbCrv7\n"
    )
    assert code == 1, out
    assert out.count("AI attribution") == 2


def test_clean_pr_text_passes_without_commit_format_rules():
    # A PR body is prose: no Conventional-Commits header, long lines are fine.
    code, out = _lint_pr("Implements #753.\n\n" + "x" * 300 + "\n")
    assert code == 0, out


def test_unknown_type_fails():
    code, _ = _lint("wibble(api): not a real conventional type here\n")
    assert code == 1


def test_empty_message_fails():
    code, _ = _lint("\n\n")
    assert code == 1


def test_merge_commit_is_allowed():
    code, _ = _lint("Merge branch 'main' into feature/x\n")
    assert code == 0


def test_comment_and_scissors_lines_are_ignored():
    # git comment lines (`# …`) and the `--verbose` scissors diff must not be
    # linted — only the author's actual message.
    message = (
        "feat(api): add a perfectly fine subject line\n"
        "\n"
        "# this is a git comment and should be ignored\n"
        "a real body line that is fine\n"
        "# ------------------------ >8 ------------------------\n"
        "diff --git a/x b/x\n"
        "+" + "z" * 200 + "\n"  # an over-long diff line below the scissors
    )
    code, _ = _lint(message)
    assert code == 0


def _lint_base_ref_env(env_value: str | None) -> tuple[int, str]:
    """Run the linter in --base-ref-env mode with a test env var."""
    env = dict(os.environ)
    if env_value is None:
        env.pop("TEST_COMMITLINT_BASE_REF", None)
    else:
        env["TEST_COMMITLINT_BASE_REF"] = env_value
    proc = subprocess.run(
        [sys.executable, str(SCRIPT), "--base-ref-env", "TEST_COMMITLINT_BASE_REF"],
        capture_output=True,
        text=True,
        encoding="utf-8",
        env=env,
    )
    return proc.returncode, proc.stdout + proc.stderr


def test_base_ref_env_unset_is_advisory():
    # Non-PR run (env var not set) must not fail the gate.
    code, out = _lint_base_ref_env(None)
    assert code == 0
    assert "unset/empty" in out


def test_base_ref_env_unresolvable_is_advisory():
    # A base ref that can't be resolved (e.g. not fetched) degrades to advisory,
    # never a false failure.
    code, _ = _lint_base_ref_env("definitely/not/a/real/ref")
    assert code == 0


def test_hyphenated_tool_name_fails():
    # Round-7 adversarial review on #754: "Claude-Code" slipped through.
    code, out = _lint(VALID_HEADER + "Body.\n\nGenerated with Claude-Code\n")
    assert code == 1, out


def test_hyphenated_prose_still_passes():
    code, out = _lint(VALID_HEADER + "Pagination created with cursor-based paging.\n")
    assert code == 0, out
