-- Security remediation: close all remaining public tables that were created
-- without RLS in the active Prisma migration chain.
--
-- This intentionally applies a secure default: enable RLS first, then add
-- table-specific policies in follow-up migrations only where direct client
-- access is required.

ALTER TABLE "activity_comments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "activity_reactions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_monitoring_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_output_review_audit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ai_output_reviews" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "alert_incidents" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "api_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "article_feedback" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "article_sections" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "audit_log_entries" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "auto_response_drafts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "calendar_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "calendars" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "chain_version_audit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "chain_versions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "contact_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "conversation_records" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "deal_renewals" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "domain_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "experiment_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "experiment_results" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "experiments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "health_checks" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "help_articles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "kpi_definitions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lead_automation_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lead_conversion_audit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lead_custom_fields" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lead_notes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lead_scoring_rules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "lead_stage_configs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notification_delivery_logs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notification_dlq" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notification_preferences" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notification_templates" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "notifications" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "performance_metrics" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "pipeline_stage_configs" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "rbac_roles" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "role_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "security_events" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "sessions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "team_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "teams" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenant_modules" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tenants" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ticket_activities" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "tickets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_mfa_settings" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_permissions" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "user_role_assignments" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "users" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workspace_members" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "workspaces" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "zep_episode_audit" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "zep_episode_usage" ENABLE ROW LEVEL SECURITY;
