# Generated by Terraform (local_file.env_template) — do not edit by hand.
# Environment: ${environment}

# --- Supabase ---
SUPABASE_URL=${supabase_url}
SUPABASE_ANON_KEY=${supabase_anon_key}
SUPABASE_SERVICE_ROLE_KEY=${supabase_service_role}
DATABASE_URL=${database_url}

# --- Vercel (frontend) ---
VERCEL_URL=${vercel_url}

# --- Railway (backend) ---
RAILWAY_API_URL=${railway_api_url}
